== Structured Concurrency in&nbsp;Action

{toc}

=== Blocking methods

Two kinds of methods:

* most depend on local resources
* some depend on an external event ⇝ _blocking_

External events may never happen, +
so blocking methods should be cancelable.

=== Interruption

_Interruption_ is that cancellation mechanism:

* on the level of threads
* cooperative
* interrupted method determines +
  how to handle interruption

=== Interruption API

Interrupted status is represented by a boolean flag.

Methods on `Thread`:

* ⚡️ `interrupt()` interrupts the thread
* 🔍 `isInterrupted()` queries the flag
* ⚠️ `interrupted()` queries _and clears_ the flag

Also: `InterruptedException`.

=== InterruptedException

Thrown by well-behaved blocking methods. +
(JDK methods reset interrupted status.)

When catching `InterruptedException`:

* clean up (quickly)
* cease computation
* if possible, rethrow
* otherwise, reinterrupt thread +
  (with `interrupt()`)

=== Cancellation

`StructuredTaskScope` supports cancellation:

* joiners can cancel a scope (e.g. on subtask failure)
* a canceled scope interrupts child threads

This allows structured cancellation. +
But requires proper handling of interrupts!

=== Code

Code, code, code, code
