== Migration To Java 9

++++
<h3>Compiling and Running on Java 9</h3>
++++

=== Of Modules And JARs

Modularized JDK and legacy JARs have to cooperate.

Two requirements:

* for the module system to work, +
everything needs to be a module
* for compatibility, the class path +
and regular JARs have to keep working


=== The Unnamed Module

The *Unnamed Module* +
contains _all_ JARs on the class path +
(including modular JARs).

* has no name (surprise!)
* can read all modules
* exports all packages

Inside the unnamed module +
"the chaos of the class path" lives on.

[NOTE.speaker]
--
* one unnamed module per class loader
--

=== Access to Internal APIs

Internal APIs are encapsulated by default.

What exactly is "internal"?

* everything not exported by a module
* includes most `com.sun.*` packages
* includes all `sun.*` packages +
except parts of `sun.misc`

`Unsafe` and others are available +
in _jdk.unsupported_ for a while.

=== Breaking Into Modules

Compilation will fail for internal dependencies:

* use `--add-exports` to export packages

In Java 9, run time access is allowed +
but reflection will result in a warning.

* use `--add-exports` to export packages
* use `--add-opens` to open packages +
for deep reflection
* use `--illegal-access` to configure behavior

=== Adding Java EE Modules

Java EE modules are not included by default:

_java.activation_, _java.corba_, _java.transaction_ +
_java.xml.bind_, _java.xml.ws_, _java.xml.ws.annotation_

Have to be added to compiler and JVM +
with `--add-modules`.

=== Splitting Packages

No two modules can contain the same packages +
(exported or not).

* for named modules this is checked
* for the unnamed module it is _not_
* classes in the unnamed package are "invisible"

=== Splitting Packages

Two ways to mend the split:

* for _upgreadable modules_, use the JAR instead +
of the module (`--upgrade-module-path`)
* for individual classes, merge the JAR with +
the module (`--patch-module`)
