== Sophisticated tests

++++
<table class="toc">
	<tr><td>First Steps</td></tr>
	<tr><td>Mechanisms</td></tr>
	<tr class="toc-current"><td>Sophisticated Tests</td></tr>
		<tr><td><ul><li>Nested Tests</li></ul></td></tr>
		<tr><td><ul><li>Repeated Tests</li></ul></td></tr>
		<tr><td><ul><li>Parameterized Tests</li></ul></td></tr>
		<tr><td><ul><li>Parallel Tests</li></ul></td></tr>
		<tr><td><ul><li>Dynamic Tests</li></ul></td></tr>
	<tr><td>From 4 To 5</td></tr>
	<tr><td>Extensions</td></tr>
</table>
++++

:toc: pass:[ \
<table class="toc"> \
	<tr><td>First Steps</td></tr> \
	<tr><td>Mechanisms</td></tr> \
	<tr><td>Sophisticated Tests</td></tr> \
		<tr class="toc-current"><td><ul><li>Nested Tests</li></ul></td></tr> \
		<tr><td><ul><li>Repeated Tests</li></ul></td></tr> \
		<tr><td><ul><li>Parameterized Tests</li></ul></td></tr> \
		<tr><td><ul><li>Parallel Tests</li></ul></td></tr> \
		<tr><td><ul><li>Dynamic Tests</li></ul></td></tr> \
	<tr><td>From 4 To 5</td></tr> \
	<tr><td>Extensions</td></tr> \
</table> \
]
include::nested-tests.adoc[]

:toc: pass:[ \
<table class="toc"> \
	<tr><td>First Steps</td></tr> \
	<tr><td>Mechanisms</td></tr> \
	<tr><td>Sophisticated Tests</td></tr> \
		<tr><td><ul><li>Nested Tests</li></ul></td></tr> \
		<tr class="toc-current"><td><ul><li>Repeated Tests</li></ul></td></tr> \
		<tr><td><ul><li>Parameterized Tests</li></ul></td></tr> \
		<tr><td><ul><li>Parallel Tests</li></ul></td></tr> \
		<tr><td><ul><li>Dynamic Tests</li></ul></td></tr> \
	<tr><td>From 4 To 5</td></tr> \
	<tr><td>Extensions</td></tr> \
</table> \
]
include::repeated-tests.adoc[]

:toc: pass:[ \
<table class="toc"> \
	<tr><td>First Steps</td></tr> \
	<tr><td>Mechanisms</td></tr> \
	<tr><td>Sophisticated Tests</td></tr> \
		<tr><td><ul><li>Nested Tests</li></ul></td></tr> \
		<tr><td><ul><li>Repeated Tests</li></ul></td></tr> \
		<tr class="toc-current"><td><ul><li>Parameterized Tests</li></ul></td></tr> \
		<tr><td><ul><li>Parallel Tests</li></ul></td></tr> \
		<tr><td><ul><li>Dynamic Tests</li></ul></td></tr> \
	<tr><td>From 4 To 5</td></tr> \
	<tr><td>Extensions</td></tr> \
</table> \
]
include::parameterized-tests.adoc[]

:toc: pass:[ \
<table class="toc"> \
	<tr><td>First Steps</td></tr> \
	<tr><td>Mechanisms</td></tr> \
	<tr><td>Sophisticated Tests</td></tr> \
		<tr><td><ul><li>Nested Tests</li></ul></td></tr> \
		<tr><td><ul><li>Repeated Tests</li></ul></td></tr> \
		<tr><td><ul><li>Parameterized Tests</li></ul></td></tr> \
		<tr class="toc-current"><td><ul><li>Parallel Tests</li></ul></td></tr> \
		<tr><td><ul><li>Dynamic Tests</li></ul></td></tr> \
	<tr><td>From 4 To 5</td></tr> \
	<tr><td>Extensions</td></tr> \
</table> \
]
include::parallel-tests.adoc[]

:toc: pass:[ \
<table class="toc"> \
	<tr><td>First Steps</td></tr> \
	<tr><td>Mechanisms</td></tr> \
	<tr><td>Sophisticated Tests</td></tr> \
		<tr><td><ul><li>Nested Tests</li></ul></td></tr> \
		<tr><td><ul><li>Repeated Tests</li></ul></td></tr> \
		<tr><td><ul><li>Parameterized Tests</li></ul></td></tr> \
		<tr><td><ul><li>Parallel Tests</li></ul></td></tr> \
		<tr class="toc-current"><td><ul><li>Dynamic Tests</li></ul></td></tr> \
	<tr><td>From 4 To 5</td></tr> \
	<tr><td>Extensions</td></tr> \
</table> \
]
include::dynamic-tests.adoc[]
