== Configuring JUnit

{toc}

=== Global configuration

These can be configured globally:

* test instance lifecycle
* deactivated conditions
* automatic extensions

(So far.)

=== Configuration parameters

A configuration parameter is +
a simple key-value pair, e.g.:

```
junit.jupiter.conditions.deactivate = *
```

=== Defining parameters

Three ways to define parameters:

* build tool
* system properties
* configuration file

(In order of decreasing precedence.)

=== With Maven

```xml
<plugin>
	<artifactId>maven-surefire-plugin</artifactId>
	<configuration>
		<properties>
			<configurationParameters>
				junit.jupiter.conditions.deactivate=*
			</configurationParameters>
		</properties>
	</configuration>
	<dependencies>
		...
	</dependencies>
</plugin>
```

=== With Gradle

```java
test {
	useJUnitPlatform()
	systemProperties = [
		'junit.jupiter.conditions.deactivate': '*'
	]
}
```

Wait, that's actually a system property!

=== With system properties

Add command line parameter +
to launching JVM:

```
-Djunit.jupiter.conditions.deactivate=*
```

=== With a properties file

Create a Java properties file:

* in `src/test/resources`
* named `junit-platform.properties`

```
junit.jupiter.conditions.deactivate=*
```

=== Defining parameters

Where best define parameters?

Consider:

* build tool configuration +
is not picked up by IDEs (yet?)
* system properties need +
to be configured manually +
for IDEs and build tools

=== Defining parameters

Where best define parameters?

* for local experiments: +
⇝ system properties
* for permanent configuration: +
⇝ properties file
