== Extensions

++++
<table class="toc">
	<tr><td>First Steps</td></tr>
	<tr><td>Mechanisms</td></tr>
	<tr><td>Sophisticated Tests</td></tr>
	<tr><td>From 4 To 5</td></tr>
	<tr class="toc-current"><td>Extensions</td></tr>
</table>
++++

=== Extensions in JUnit 4
==== Runners

Manage a test's full lifecycle.

```java
@RunWith(MockitoJUnitRunner.class)
public class MyTest { ... }
```

* very flexible
* heavyweight
* exclusive

=== Extensions in JUnit 4
==== Rules

Execute code before and after statements.

```java
public class MyTest {
	@Rule
	public MockitoRule rule =
		MockitoJUnit.rule();
}
```

* added in 4.7
* lightweight
* limited to before/after behavior

=== Extensions in JUnit 4

Extension model is not optimal:

* two competing mechanisms
** each with limitations
** but with considerable overlap
* composition can cause problems

=== Approaching extensions

From JUnit 5's
https://github.com/junit-team/junit5/wiki/Core-Principles[Core Principles]:

> Prefer extension points over features

Quite literally, +
JUnit 5 has _Extension Points_

=== Extension points

* instance post processor
* template invocation
* execution condition
* `@BeforeAll` and `@BeforeEach`
* parameter resolution
* before test execution
* after test execution
* exception handling
* `@AfterEach` and `@AfterAll`

=== Implementing extensions

* one interface for each extension point
* method arguments capture context

```java
public interface BeforeEachCallback
		extends Extension {

	void beforeEach(ExtensionContext context);
}
```

* an extension can use multiple points +
to implement its feature

=== Benchmark extension

We want to benchmark our tests!

* for each test method
* write the elapsed time to console

How?

* before test execution: store test launch time
* after test execution: print elapsed time

=== Benchmark extension

```java
public class BenchmarkExtension implements
		BeforeTestExecutionCallback,
		AfterTestExecutionCallback {

	private long launchTime;

	// ...
}
```

=== Benchmark extension

```java
@Override
public void beforeTestExecution(
		ExtensionContext context) {
	launchTime = currentTimeMillis();
}

@Override
public void afterTestExecution(
		ExtensionContext context) {
	printf("Test '%s' took %d ms.%n",
		context.getDisplayName(),
		currentTimeMillis() - launchTime);
}
```

=== Other examples

Remember This?

```java
@Test
@DisabledOnFriday
void failingTest() {
	assertTrue(false);
}
```

Let's see how it works!

=== Disabled extension

```java
public class DisabledOnFridayCondition
		implements ExecutionCondition {

	@Override
	public ConditionEvaluationResult evaluate(
			ExtensionContext context) {
		if (isFriday())
			return disabled("Weekend!");
		else
			return enabled("Fix it!");
	}

}
```

=== Other examples

What about parameter injection?

```java
@Test
void someTest(MyServer server) {
	// do something with `server`
}
```

=== Parameter injection

```java
public class MyServerParameterResolver
		implements ParameterResolver {

	@Override
	public boolean supportsParameter(
			ParameterContext pCtx, /*...*/) {
		return MyServer.class
			== pCtx.getParameter().getType();
	}

	@Override
	public Object resolveParameter(
			ParameterContext pCtx, /*...*/) {
		return new MyServer();
	}

}
```

=== Extension context

Quick look at `ExtensionContext`:

```java
// every node has its own context
Optional<ExtensionContext> getParent();
ExtensionContext getRoot();

// some node-related info
String getUniqueId();
String getDisplayName();
Set<String> getTags();

// don't use System.out !
void publishReportEntry(String key, String value);

// configure your extension with system properties
Optional<String> getConfigurationParameter(String key)
```

=== Extension context

Quick look at `ExtensionContext`:

```java
// to reflect over the test class/method
Optional<AnnotatedElement> getElement();
Optional<Class<?>> getTestClass();
Optional<Method> getTestMethod();
Optional<Lifecycle> getTestInstanceLifecycle();

// use the store to safe extension state
Store getStore(Namespace namespace);
```

=== Stateless extensions

JUnit makes no promises regarding +
extension instance lifecycle!

*⇝ Extensions must be stateless!*

Use the `Store`, Luke!

* namespaced
* hierarchical
* key-value

=== Extension store
==== Namespaced

Store is accessed via `ExtensionContext` +
given a `Namespace`:

```java
Store getStore(Namespace namespace);
```

* keeps extensions from stepping +
on each other's toes
* could allow deliberate communication!

=== Extension store
==== Hierarchical

Reads from the store forward to parent stores:

* method store ⇝ class store
* nested class store ⇝ surrounding class store

Writes always go to the called store.

=== Extension store
==== Key-Value

The store is essentially a map:

```java
Object getObject(Object key);
Object getOrComputeIfAbsent(
		K key, Function creator);

void put(Object key, Object value)

Object remove(Object key)
```

Overloads with type tokens exist.

=== Stateless benchmark

```java
void storeNowAsLaunchTime(
		ExtensionContext context) {
	long now = currentTimeMillis();
	context.getStore(NAMESPACE)
			.put(KEY, now);
}

long loadLaunchTime(
		ExtensionContext context) {
	return context.getStore(NAMESPACE)
			.get(KEY, long.class);
}
```

=== Breather

Where were we?

* extensions implement interfaces
* use `ExecutionContext` for interaction
* use `Store` to be stateless

We know how to create extensions.

How do we apply them?

=== Registering extensions

Three ways to register extensions:

* declarative with `@ExtendWith`
* programmatically with `@RegisterExtension`
* automatically with service loader

=== Declarative

Use `@ExtendWith` to register extension +
with annotation:

```java
@ExtendWith(DisabledOnFridayCondition.class)
class SomeTest {
	...
}
```

That's technical and verbose... :(

=== Declarative

https://en.wikibooks.org/wiki/Java_Programming/Annotations/Meta-Annotations[Meta-annotations] to the rescue!

* JUnit 5's annotations are meta-annotations
* JUnit 5 checks recursively for annotations

⇝ We can create our own annotations!

=== Creating annotations

```java
@ExtendWith(DisabledOnFridayCondition.class)
public @interface DisabledOnFriday { }

@Test
@Tag("integration")
@ExtendWith(BenchmarkExtension.class)
@ExtendWith(MyServerParameterResolver.class)
public @interface IntegrationTest { }

@IntegrationTest
@DisabledOnFriday
void testLogin(MyServer server) { ... }
```

=== Programmatic

Annotations only accept +
compile time constants.

```java
@DisabledByFormula(
	"After Mayan b'ak'tun 13",
	// Nope 😩
	now().isAfter(MAYAN_B_AK_TUN_13))
class DisabledByFormulaTest {

	private static final LocalDateTime
		MAYAN_B_AK_TUN_13 = of(2012, 12, 21, 0, 0);
}
```

=== Programmatic

Instead declare extension as field +
and annotate with `@RegisterExtension`:

```java
class DisabledByFormulaTest {

	private static final LocalDateTime
		MAYAN_B_AK_TUN_13 = of(2012, 12, 21, 0, 0);

	@RegisterExtension
	static DisabledByFormula FORMULA = disabledWhen(
			"After Mayan b'ak'tun 13",
			now().isAfter(MAYAN_B_AK_TUN_13));
}
```

=== Automatic

You can use Java's service loader +
to register extensions globally, +
(i.e. without putting them into code) +
but I won't go into it here.

⇝ https://junit.org/junit5/docs/current/user-guide/#extensions-registration-automatic[User guide on global registration].

=== Extensions
==== Summary

* many extension points provide +
flexibility and composability
* extensions implement various interfaces
* can access test context and a store
* are usually registered via meta-annotations

⇝ Read http://blog.codefx.org/design/architecture/junit-5-extension-model/[more about extensions].
