== Setup & Tools

{toc}

=== Writing tests

Add test dependency:

```shell
org.junit.jupiter
junit-jupiter-api
5.2.0
```

Have fun!

=== Writing tests

No specific test library support required. +
These all work out of the box:

* Mockito, PowerMock
* AssertJ, Google Truth, +
Hamcrest, FestAssert

=== Running tests

Add test dependency:

```shell
org.junit.jupiter
junit-jupiter-engine
5.2.0
```

=== Running tests

With build tools:

* *Maven*:
** since Surefire 2.22.0
** add `test` dependency on engine
* *Gradle*:
** since 4.6
** add `testRuntime` dependency on engine
** activate JUnit 5:
+
[source,groovy]
----
test {
	useJUnitPlatform()
}
----

=== Running tests

With IDEs:

* *IntelliJ*: since https://blog.jetbrains.com/idea/2016/08/using-junit-5-in-intellij-idea/[2016.2],
but https://blog.jetbrains.com/idea/2017/11/intellij-idea-2017-3-junit-support/[2017.3] recommended
* *Eclipse*: since https://www.eclipse.org/eclipse/news/4.7.1a/#junit-5-support"[Oxygen.1a (4.7.1a)]
// search for all issues with "JUnit" in them:
// https://netbeans.org/bugzilla/buglist.cgi?quicksearch=JUnit%205
* *NetBeans*: not even an issue

=== Running tests

As part of JUnit 4

* individual classes:
+
```java
@RunWith(JUnitPlatform.class)
public class JUnit5Test { ... }
```
* all classes:
+
```java
@RunWith(JUnitPlatform.class)
@SelectPackages({ "my.test.package" })
public class JUnit5TestSuite { }
```

=== Running tests

There is a console launcher:

```bash
# run all tests
java -jar junit-platform-console-standalone.jar
	--class-path ${path_to_compiled_test_classes}
	--scan-class-path
# run a specific test
java -jar junit-platform-console-standalone.jar
	--class-path ${path_to_compiled_test_classes}
	--select-class ${fully_qualified_test_class_name}
```

=== Setup & Tools
==== Summary

* native support in Maven, Gradle, IntelliJ, Eclipse +
(remember to add the engine as dependency)
* for outdated tools, run with JUnit 4
* console launcher as last resort

⇝ http://blog.codefx.org/libraries/junit-5-setup/[More about setup details].
