== Image Credits

=== advent-calendar.jpg

https://www.flickr.com/photos/littlestuffme/10599733413[Advent Calendar]:
https://www.flickr.com/photos/littlestuffme/[Tina D]
(https://creativecommons.org/licenses/by/2.0/[CC-BY 2.0])

=== advent-calendar-shop.jpg

https://www.flickr.com/photos/ambernectar/6214119489/

=== ball-of-mud.jpg

https://www.flickr.com/photos/benhaeringer/8247853366/[Mistkäfer]:
https://www.flickr.com/photos/benhaeringer/[Ben Haeringer]
(https://creativecommons.org/licenses/by-nd/2.0/[CC-BY-ND 2.0])

=== ball-of-mud-2.jpg

https://www.flickr.com/photos/elgentscho/6883404352/[Dung Beetle @ Work]:
https://www.flickr.com/photos/elgentscho/[Andi Gentsch]
(https://creativecommons.org/licenses/by-sa/2.0/[CC-BY-SA 2.0])

=== binary-code.jpg

https://www.flickr.com/photos/132889348@N07/20607150556/[Binary Code]:
https://www.flickr.com/photos/132889348@N07/[Christiaan Colen]
(https://creativecommons.org/licenses/by-sa/2.0/[CC-BY-SA 2.0])

=== broken-glass.jpg

https://www.flickr.com/photos/akeg/2230862848/[Broken Glass at Work-6]
https://www.flickr.com/photos/akeg/[Eric Schmuttenmaer]
(https://creativecommons.org/licenses/by-sa/2.0/[CC-BY-SA 2.0])

=== bundles.jpg

https://www.flickr.com/photos/dmahendra/5758053768/[Bundles]
https://www.flickr.com/photos/dmahendra/[Danumurthi Mahendra]
(https://creativecommons.org/licenses/by/2.0/[CC-BY 2.0])

=== cells.jpg

https://www.flickr.com/photos/jonolist/3338861834/[Cells]
https://www.flickr.com/photos/jonolist/[Jonathan Lin]
(https://creativecommons.org/licenses/by-sa/2.0/[CC-BY-SA 2.0])

=== confusion.jpg

https://www.flickr.com/photos/procsilas/8116870793/[Confusion]
https://www.flickr.com/photos/procsilas/[Procsilas Moscas]
(https://creativecommons.org/licenses/by/2.0/[CC-BY 2.0])

=== cut.jpg

https://www.flickr.com/photos/span112/2889438473/[Cut]
https://www.flickr.com/photos/span112/[Jinx!]
(https://creativecommons.org/licenses/by-sa/2.0/[CC-BY-SA 2.0])

=== disy-landscape.jpg

© http://www.disy.net/en/welcome.html[Disy Informationssysteme GmbH]

=== flag-amsterdam.jpg

https://www.flickr.com/photos/rogersg/9489328988/[Amsterdam / Flag]
https://www.flickr.com/photos/rogersg/[George Rex]
(https://creativecommons.org/licenses/by-sa/2.0/[CC-BY-SA 2.0])

=== garbage-only.jpg

https://www.flickr.com/photos/peterkaminski/17964466[Garbage Only]:
https://www.flickr.com/photos/peterkaminski/[Peter Kaminski]
(https://creativecommons.org/licenses/by/2.0/[CC-BY 2.0])

=== golden-gate.jpg

https://www.flickr.com/photos/82955120@N05/11702702564[Golden Dawn Bridge - HDR]:
https://www.flickr.com/photos/82955120@N05/[Nicolas Raymond]
(https://creativecommons.org/licenses/by/2.0/[CC-BY 2.0])

=== graph.png

https://www.flickr.com/photos/chef_ele/3790471493[NetflixPrize-MovieMap-NoTitles-RedYellowOnBlack]:
https://www.flickr.com/photos/chef_ele/[chef_ele]
(https://creativecommons.org/licenses/by/2.0/[CC-BY 2.0])

=== iceberg.jpg

https://www.flickr.com/photos/usoceangov/8290528771[Iceberg]:
https://www.flickr.com/photos/usoceangov/[NOAA's National Ocean Service]
(https://creativecommons.org/licenses/by/2.0/[CC-BY 2.0])

=== internal.jpg

https://www.flickr.com/photos/generated/85543402/[Internal]
https://www.flickr.com/photos/generated/[Jared Tarbell]
(https://creativecommons.org/licenses/by/2.0/[CC-BY 2.0])

=== internals.jpg

https://www.flickr.com/photos/thedonquixotic/16851988305[Internals]
https://www.flickr.com/photos/thedonquixotic/[David French]
(https://creativecommons.org/licenses/by/2.0/[CC-BY 2.0])

=== jar-hell.jpg

https://commons.wikimedia.org/wiki/File:An_angel_leading_a_soul_into_hell._Oil_painting_by_a_followe_Wellcome_L0030887.jpg[An Angel Leading A Soul Into Hell]:
https://wellcomelibrary.org/[Wellcome Library, London]
(https://creativecommons.org/licenses/by/4.0/[CC-BY 4.0])

=== keep-out.jpg

https://www.flickr.com/photos/smithser/8441579102[Keep Out!]:
https://www.flickr.com/photos/smithser/[Brian Smithson]
(https://creativecommons.org/licenses/by/2.0/[CC-BY 2.0])

=== obsolete.jpg

https://www.flickr.com/photos/trevor-king/12419679154/[#4 Obsolete]
https://www.flickr.com/photos/trevor-king/[Trevor King]
(https://creativecommons.org/licenses/by/2.0/[CC-BY 2.0])

=== puzzle-cubed.jpg

https://www.flickr.com/photos/dps/136564771[Puzzle Cubed]
https://www.flickr.com/photos/dps/[David Singleton]
(https://creativecommons.org/licenses/by/2.0/[CC-BY 2.0])

=== puzzle-people.jpg

https://www.flickr.com/photos/pagedooley/14555354976/[Puzzle]
https://www.flickr.com/photos/pagedooley/[Kevin Dooley]
(https://creativecommons.org/licenses/by/2.0/[CC-BY 2.0])

=== puzzle-piece-green.jpg

https://www.flickr.com/photos/86530412@N02/8252117202/[3D Green Puzzle Piece]
http://www.stockmonkeys.com/[StockMonkeys.com]
(https://creativecommons.org/licenses/by/2.0/[CC-BY 2.0])

=== puzzle-pieces-put-together.jpg

https://www.flickr.com/photos/teegardin/6147270119/[Putting The Puzzle Together]
http://www.seniorliving.org[Ken Teegardin]
(https://creativecommons.org/licenses/by-sa/2.0/[CC-BY-SA 2.0])

=== puzzle-pieces.jpg

https://www.flickr.com/photos/lizadaly/2945260782/[Puzzle Pieces]
https://www.flickr.com/photos/lizadaly/[Liza]
(https://creativecommons.org/licenses/by/2.0/[CC-BY 2.0])

=== question-mark.jpg

https://www.flickr.com/photos/21496790@N06/5065834411[sensitive noise]
http://milosevicmilos.com/[Milos Milosevic]
(https://creativecommons.org/licenses/by/2.0/[CC-BY 2.0])

=== sign.jpg

https://www.flickr.com/photos/duncharris/3734701772/[Sign]
https://www.flickr.com/photos/duncharris/[Duncan Harris]
(https://creativecommons.org/licenses/by-sa/2.0/[CC-BY-SA 2.0])
