== {title}

{toc}

=== Quantum computers

> The fusion reactors of computer science

Today: ::
Can barely factor 35 into 5*7 (https://arxiv.org/html/2410.14397v1[source]).

Soon™: ::
Can factor numbers in polynomial time and space +
(and thus break many encryption algorithms).

In the meantime: ::
Harvest now, decrypt later.

=== Post-quantum encryption

NIST standardized module-latice based algorithms:

* ML-KEM to secure symmetric keys (https://csrc.nist.gov/pubs/fips/203/final[FIPS 203])
* ML-DSA for digital signatures (https://csrc.nist.gov/pubs/fips/204/final[FIPS 204])

IETF developed a framework for +
hybrid key exchange schemes for TLS 1.3 (https://www.rfc-editor.org/info/rfc9954/[RFC 9954]).

=== PQC in Java

JDK 27 implements:

* ML-KEM for keys
* ML-DSA for signatures
* hybrid key exchange for TLS 1.3

(Oracle announced backports to +
Oracle JDKs 25, 21, 17, 11, 8.)

=== PQC in TLS 1.3

New named groups:

* `X25519MLKEM768 = ECDHE/X25519 + ML-KEM-768` +
  (fastest and most commonly used)
* `SecP256r1MLKEM768 = ECDHE/secp256r1 + ML-KEM-768`
* `SecP384r1MLKEM1024 = ECDHE/secp384r1 + ML-KEM-1024`

When exchanging supported schemes, +
JDK 27 places `X25519MLKEM768` first.

⇝ PQC is selected (if supported) +
without configuration changes.

=== Configuring PQC

Scheme list can be configured with `jdk.tls.namedGroups`.

Or when configuring a socket connection:

```java
var socket = (SSLSocket) SSLContext
	.getDefault().getSocketFactory().createSocket();
var params = socket.getSSLParameters();

params.setNamedGroups(new String[] {
	"SecP256r1MLKEM768", "X25519MLKEM768",
	"secp256r1", "x25519"
});
socket.setSSLParameters(params);
```

=== Countless improvements

A random collection:

* HTTP response body size limits
* integrity disallows by default: +
  JNI, final field mutation, dynamic agents
* `Unsafe` memory access is deprecated +
  and disabled by default
* JFR's initial security property logging
* JFR's data redaction
* `keytool` warns about weak PBE algorithms
* updates to countless algorithms, +
  key lengths, default values, etc.

=== PEM texts

Representations of cryptographic objects +
(keys, certificates, certificate revocation lists):

```
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj
0DAQcDQgAEi/kRGOL7wCPTN4KJ
2ppeSt5UYB6ucPjjuKDtFTXbgu
OIFDdZ65O/8HTUqS/sVzRF+dg7
H3/tkQ/36KdtuADbwQ==
-----END PUBLIC KEY-----
```

=== PEM API

PEM API encodes and decodes cryptographic objects:

```java
X509Certificate cert = // ...

// encode
PEMEncoder encoder = PEMEncoder.of();
String pem = encoder.encodeToString(cert);

// decode
PEMDecoder decoder = PEMDecoder.of();
BinaryEncodable cert2 = decoder.decode(pem);

assert cert.equals(cert2);
```

=== Encodable

All implementations of `BinaryEncodable` can be encoded:

* `AsymmetricKey` +
  (DH, DSA, EC, RSA, etc.)
* `KeyPair`
* `PKCS8EncodedKeySpec`
* `X509EncodedKeySpec`
* `X509Certificate`
* `X509CRL`
* `EncryptedPrivateKeyInfo`
* `PEM`

=== Decoding

For decoding:

* if the object type is known, call +
  `decode(String, Class<T extends BinaryEncodable>)`:
+
```java
KeyPair kp = decoder.decode(pem, KeyPair.class);
```
* otherwise, switch over return value of `decode(String)`

=== Monthly updates

* AI increased speed/scale of +
  vulnerability discovery/remediation
* Oracle intends to shift security updates +
  for OracleJDK from quarterly to monthly
* will probably knock-on to other distributions

Keep an eye out for unexpected patch releases!

=== Versions

JDK 24: ::
* ML-KEM & ML-DSA

JDK 27: ::
* TLS 1.3 with PQC

JDK 28: ::
* PEM API

=== Summary

Supported Java versions get regular security patches +
(starting in 2027: probably monthly).

New Java versions get additional security features +
(which may be backported if important).

Either way, stay up to date!
