== Public Service Announcement

* new release schedule
* Oracle JDK ≠ OpenJDK
* Java on the desktop

=== New Release Schedule

New feature release every six months:

* Sep 2017: Java 9
* Mar 2018: Java 10
* *Sep 2018: Java 11*
* Mar 2019: Java 12

=== Oracle JDK ≠ OpenJDK

* Oracle JDK 11+ is fully commercial
* Oracle ships OpenJDK builds
* but *only for current major version*: +
⇝ 10 ⇝ 10.0.1 ⇝ 10.0.2 +
⇝ 11 ⇝ 11.0.1 ⇝ 11.0.2 (*Dec 2018*) +
⇝ 12 ⇝ 12.0.1 ⇝ 12.0.2 +
* there is no pass:[<span style="text-decoration: line-through;">spoon</span>] free LTS by Oracle!

⇝ More on my blog: +
*All You Need To Know For Migrating To Java 11*
https://blog.codefx.org/java/java-11-migration-guide/[http://tiny.cc/java-11]

=== Java on the desktop

In March 2018, Oracle released a +
_Java Client Roadmap Update_ (https://www.oracle.com/technetwork/java/javase/javaclientroadmapupdate2018mar-4414431.pdf[PDF]).

Describes plans for:

* Applets
* Web Start
* JavaFX
* Swing/AWT

=== Applets & Web Start

* deprecated in Java SE 9
* removed from Java SE 11
* not in Oracle's JDK 11 builds

=== JavaFX

* was never part of Java SE
* was never in Oracle's OpenJDK builds
* not in Oracle's JDK 11 builds
* now standalone project at https://openjfx.io/[openjfx.io]

If your project uses JavaFX, +
you *can't rely* on its presence +
on your customers' machines!

⇝ Bring it along as dependency.

=== JavaFX

Quote:

++++
<div class="quoteblock"><blockquote style="color: black;">
Oracle is working with interested third parties to make it easier to build and maintain JavaFX as a separately distributable open-source module.
</blockquote></div>
++++

Not a quote:

++++
<div class="quoteblock"><blockquote style="color: black;">
Oracle wants to reduce/terminate investment in JavaFX.
</blockquote></div>
++++

=== Swing/AWT

Quote:

++++
<div class="quoteblock"><blockquote style="color: black;">
Oracle will continue developing Swing and AWT in Java SE 8 and Java SE 11 (18.9 LTS).
This means they will be supported by Oracle through at least 2026.
</blockquote></div>
++++

What this doesn't say:

* support is free
* support goes beyond Java 11

=== Swing/AWT

*Hypothetically* Oracle could +
remove Swing/AWT from Java SE 12 +
and its statement still holds.

⇝ More in my newsletter: +
https://medium.com/codefx-weekly/java-desktop-quo-vadis-f0803166e36b[Java Desktop, Quo Vadis?]

=== More PSAs

To hear about such news:

* follow me on Twitter: https://twitter.com/nipafx[@nipafx]
* subscribe to my newsletter: https://nipafx.dev/news[nipafx.dev/news]
