== Pattern Matching and Beyond

++++
<table class="toc">
	<tr><td>Data-Oriented Programming</td></tr>
	<tr><td>A Lengthy Example</td></tr>
	<tr class="toc-current"><td>Project Amber's Arc</td></tr>
</table>
++++

=== Project Amber

All the new features we just used +
were developed by Project Amber.

Profile:

* https://openjdk.org/projects/amber/[project] /
https://wiki.openjdk.org/display/amber/Main[wiki] /
https://mail.openjdk.org/mailman/listinfo/amber-dev[mailing list]
* launched March 2017
* led by Brian Goetz

=== Patterns so far...

In `instanceof` and `switch`, patterns can:

* match against reference types
* deconstruct records
* nest patterns
* ignore parts of a pattern

In `switch`:

* refine the selection with guarded patterns

=== Patterns so far...

That (plus sealed types) are +
the pattern matching _basics_.

This will be:

* built up with more features
* built out to re-balance the language

=== Case in Point

The `x instanceof Y` operation:

* meant: "is `x` of type `Y`?"
* now means: "does `x` match the pattern `Y`?"

For primitives:

* old semantics made no sense +
  ⇝ no `x instanceof $primitive`
* new semantics _can_ make sense

=== Bound Checks

Example A: `int x = 0;`

* `x` can't literally be an instance of `byte`
* but its value can be a `byte`

Example B: `int y = 16_777_217;`

* `y` can't literally be an instance of `float`
* it can be cast to a `float` but not losslessly

=== Conversion checks

Primitive patterns for simpler conversion checks:

```java
int x = 0;
if (x instanceof byte b)
	IO.println(b + " in [-128, 127]");

int y = 16_777_217;
if (y instanceof float f)
	IO.println(f + " is a float (lossless)");
```

(Probably sixth preview in JDK 28.)

=== Strawman syntax

Everything coming next is speculative, +
particularly the syntax!

⚠️

=== Constant checks

Constant patterns for simpler primitive checks:

```java
record Point(int x, int y) { }

var point = // ...
switch (point) {
	// primitive pattern
	case Point(var x, _) when x == 0 -> // ...
	// constant pattern (probably)
	case Point(0, _) -> // ...
}
```

Currently, only records can be deconstructed.

=== Deconstructible interfaces

Expand deconstruction to other types:

```java
// ↙ INTERFACE   ↙ state description
interface Point(int x, int y) {
	// state description implicitly requires:
	// int x();
	// int y();
}

// would allow
var point = // ...
switch (point) {
	case Point(var x, var y) -> // ...
}
```


=== Deconstruction on assignment

Often, there's no need for the conditional.

Deconstruction on assignment is unconditional:

```java
// `Point` is a type with state description
Point nextPoint() { /* ... */ }

// if you only need `x`
Point(int x, _) = nextPoint();
```

=== Reconstruction

If the type has a symmetrical construction protocol +
(like records):

```java
record Point(int x, int y) { }

var p0 = new Point(0, 0);
var p1 = p0 with { x = 1; };
```

=== More

Patterns and deconstruction:

* 📝 https://openjdk.org/jeps/532[JEP 532]: Primitive Types in Patterns
* 🎥 https://www.youtube.com/watch?v=_afECXGjfDI[Restoring the Balance with Primitive Patterns]
* 📝 https://openjdk.org/jeps/8357464[JEP draft]: Enhanced Local Variable Declarations
* 📝 https://openjdk.org/jeps/468[JEP 468]: Derived Record Creation
* 📝 mails https://mail.openjdk.org/pipermail/amber-spec-experts/2026-January/004307.html[#1], https://mail.openjdk.org/pipermail/amber-spec-experts/2026-February/004351.html[#2] on deconstruction of classes

Other endeavors:

* string templates (yes, still)
* 🎥 talks https://www.youtube.com/watch?v=fbqAyRJoQO0[#1], https://www.youtube.com/watch?v=R8Xubleffr8[#2] on serialization 2.0
* 📝 https://openjdk.org/jeps/8209434[JEP draft]: Concise Method Bodies
