== Data-Oriented Programming

++++
<table class="toc">
	<tr class="toc-current"><td>What is DOP?</td></tr>
	<tr><td>A Lengthy Example</td></tr>
	<tr><td>That was DOP!</td></tr>
</table>
++++

=== Programming Paradigms

> The goal of any programming paradigm is to manage complexity.

* complexity comes in many forms
* not all paradigms handle all forms equally well

â‡ "It depends"

=== Object-Oriented Programming

> Everything is an object

* combines state and behavior
* hinges on encapsulation
* polymorphism through inheritance

Works best when defining/upholding boundaries.

[NOTE.speaker]
--
* maintenance boundaries
* versioning boundaries
* encapsulation boundaries
* compilation boundaries
* compatibility boundaries
* security boundaries
--

=== Mixed Programming

Great use cases for OOP:

* boundaries between libraries and clients
* in large programs to enable modular reasoning

Consider a data-oriented approach for:

* smaller (sub)systems
* focused on data

=== Guiding Principles

Brian Goetz formulated them in June 2022: +
https://www.infoq.com/articles/data-oriented-programming-java/[Data Oriented Programming in Java]

I offered an updated version in May 2024: +
https://inside.java/2024/05/23/dop-v1-1-introduction/[Data-Oriented Programming in Java - Version 1.1]

=== Data-Oriented Programming

Version 1.1:

* Model data immutably and transparently.
* Model the data, the whole data, +
  and nothing but the data.
* Make illegal states unrepresentable.
* Separate operations from data.
