== Java 8

++++
<table class="toc">
	<tr><td>Generics Recap ⑤</td></tr>
	<tr><td>Lambda Expressions</td></tr>
	<tr><td>Stream API</td></tr>
	<tr><td>Optional API</td></tr>
	<tr><td>Functional Programming Basics</td></tr>
	<tr><td>CompletableFuture API</td></tr>
	<tr class="toc-current"><td>Default Methods</td></tr>
	<tr><td>Summary</td></tr>
</table>
++++

=== Mmh...

Where does `Collection::stream` come from?

* new method on a public interface
* breaks all third-party implementations

=== Collection::stream

Take a look at `Collection` interface:

```java
default Stream<E> stream() {
	return StreamSupport.stream(spliterator(), false);
}
```

* what's `default`?
* why is there a method body?

== Default Methods

++++
<table class="toc">
	<tr class="toc-current"><td>Syntax &amp; Semantics</td></tr>
	<tr><td>Existing Functionality</td></tr>
	<tr><td>Kinds of Default Methods</td></tr>
	<tr><td>Summary</td></tr>
</table>
++++

=== Intention

* add methods to interfaces +
without breaking implementations
* extend existing interfaces +
to improve usability
* easy programming model

=== Default Method Syntax

```java
// in `List`
default void sort(Comparator<? super E> c) {
	// do the sorting
}
```

* keyword `default`
* regular method signature and body
* automatically `public` (as usual)

=== Resolution Strategy

Rule #1::
Classes win over interfaces.
Rule #2::
More specific interfaces win over less specific ones.
Rule #3::
There's no Rule #3.

=== Implications of Rule #1

(_Classes win over interfaces_)

* it is not possible to have default implementation +
of methods on `Object` (e.g. `equals`/`hashCode`)
* it is possible to "reabstract" methods:
+
```java
abstract class MyCollection<E>
		implements Collection<E> {

	public abstract Stream<E> stream();

}
```

=== Implications of Rule #2

(_More specific interfaces win over less specific ones._)

An interface extending another can provide +
a more suitable default implementation.

=== Example for Rule #2

```java
// in `Map`
default V getOrDefault(Object key, V defaultValue) {
	V v;
	return (((v = get(key)) != null) || containsKey(key))
		? v
		: defaultValue;
}

// in `ConcurrentMap`
default V getOrDefault(Object key, V defaultValue) {
	V v;
	return ((v = get(key)) != null) ? v : defaultValue;
}
```

=== Implications of Rule #3

(_There's no Rule #3_)

Occasional compile errors +
that have to be fixed manually.

Two choices:

* you can properly implement the method
* you can call a specific default method:
+
```java
public void collidingMethod() {
	ImplementedInterface.super
		.collidingMethod();
}
```

=== Exercise 1

Adding default methods and +
observing resolution strategy.

=== Static Interface Methods

Interfaces can now also have static methods. +
(*These are not "static default" methods!*)

Syntax as usual:

```java
public static <T> Comparator<T> nullsLast(
		Comparator<? super T> comparator) {
	return new Comparators
		.NullComparator<>(false, comparator);
}
```

=== Static Interface Methods

Use cases:

* factory methods for implementations +
(e.g. `List::of`; if you can bare it)
* utility methods for an interface +
(e.g. `Predicate::not`)

=== Private Interface Methods

Interfaces can now also have private methods. ⑨ +
(*These are not "private default" methods!*)

Syntax as usual:

```java
private String concat(String... args);
	// ...
}
```

=== Private Interface Methods

Use case:

Reusing code in default methods.


== Default Methods

++++
<table class="toc">
	<tr><td>Syntax &amp; Semantics</td></tr>
	<tr class="toc-current"><td>Existing Functionality</td></tr>
	<tr><td>Kinds of Default Methods</td></tr>
	<tr><td>Summary</td></tr>
</table>
++++

=== Existing Functionality

Many functional interfaces have +
usability default methods:

* Collections
* `Comparator`
* functional interfaces

=== Collections

* `Iterable.forEach(Consumer<T>)`
* `Collection.removeIf(Predicate<E>)`
* `Collection.stream()`
* `List.replaceAll(UnaryOperator<E>)`
* `List.sort(Comparator<E>)`

Many more on various collections.

=== Comparator

```java
Comparator<Todo> comparator = Comparator
	.comparing(todo -> todo.due());
comparator = comparator.reversed();
comparator = Comparator.nullsLast(comparator);
```

(Many more.)

=== Functional Interfaces

* `Function.andThen(Function<R, V>)`
* `Function.identity()`
* `Predicate.and(Predicate<T>)`
* `Predicate.negate()`


== Default Methods

++++
<table class="toc">
	<tr><td>Syntax &amp; Semantics</td></tr>
	<tr><td>Existing Functionality</td></tr>
	<tr class="toc-current"><td>Kinds of Default Methods</td></tr>
	<tr><td>Summary</td></tr>
</table>
++++

=== Three Kinds

Default methods come in three flavors:

* "optional" methods
* "reasonable" implementations
* "definitive" implementations

=== "Optional" methods

Barely useful implementation:

```java
// in Iterator
default void remove() {
	throw new UnsupportedOperationException("remove");
}
```

* fulfill (weak) contract
* look for them when +
implementing interface

=== "Reasonable" Implementation

Useful implementation:

```java
// in Iterator
default void forEach(Consumer<? super E> consumer) {
	while (hasNext())
		consumer.accept(next());
}
```

* safe to use
* might be overridden for better implementation

=== "Definitive" Implementation

Sometimes, there isn't really +
any other possible implementation:

```java
default Predicate<T> and(Predicate<? super T> p) {
	Objects.requireNonNull(p);
	return (T t) -> test(t) && p.test(t);
}
```


== Default Methods

++++
<table class="toc">
	<tr><td>Syntax &amp; Semantics</td></tr>
	<tr><td>Existing Functionality</td></tr>
	<tr><td>Kinds of Default Methods</td></tr>
	<tr class="toc-current"><td>Summary</td></tr>
</table>
++++

=== Summary

Syntax & Semantics:

* interfaces can have instance methods:
** add `default` keyword
** implement as usually
* method resolution:
** methods from classes are _always_ preferred
** default methods are "fall back"
* interface can have static and private +
methods just like classes

=== Summary

Many existing and new interfaces +
have default methods.

Specific use cases:

* create fluent decorator APIs
* evolve interfaces without breaking clients
