== Optional

++++
<table class="toc">
	<tr><td>Lambda Expressions</td></tr>
	<tr><td>Stream API</td></tr>
	<tr class="toc-current"><td>Optional API</td></tr>
	<tr><td>FP Basics</td></tr>
	<tr><td>Default Methods</td></tr>
</table>
++++


=== Motivation

Some terminal stream operations +
may not have a result:

```java
List<Todo> todos = // ...
todos.stream()
	.filter(todo -> todo.importance() == VERY)
	.findAny();
```

What should they return?

=== Motivation

Returning `null`:

* leads to buggy code (NPEs)
* leads to ugly code (`null` checks)

Instead return a type that signals +
"there might not be a result" +
but never `null`.

⇝ `Optional`!

Same logic applies to your code!


== Optional Basics

++++
<table class="toc">
	<tr class="toc-current"><td>Optional Basics</td></tr>
	<tr><td>The Imperative Way</td></tr>
	<tr><td>The Functional Way</td></tr>
	<tr><td>Optionals In Streams</td></tr>
	<tr><td>Summary</td></tr>
</table>
++++

=== What Is Optional?

`Optional<T>`:

* is a regular type
* a container for zero or one elements:
** `Optional` can be _empty_ / value is _absent_
** `Optional` can be _non-empty_ / value is _present_
** a `null` value counts as absent
* has imperative and functional APIs +
to work with absent and present values

=== Creating An Optional

Three ways to create an `Optional` yourself:

* `Optional.of(T)` expects non-`null` value
* `Optional.empty()` creates an empty optional
* `Optional.ofNullable(T)` does the right thing

Prefer using `of` and `empty` +
to make code more expressive +
and to fail early.

=== Working With Optional

The imperative way:

* checks presence
* gets value out
* processes it further

The functional way:

* uses Stream-like methods (`filter`, `map`, etc.)
* keeps `Optional` around as long as possible


== The Imperative Way

++++
<table class="toc">
	<tr><td>Optional Basics</td></tr>
	<tr class="toc-current"><td>The Imperative Way</td></tr>
	<tr><td>The Functional Way</td></tr>
	<tr><td>Optionals In Streams</td></tr>
	<tr><td>Summary</td></tr>
</table>
++++

=== Checking Presence

To check whether value is present:

* `isPresent()` returns `true`/`false`
* `isEmpty()` returns `!isPresent()` ⑪

Remember: `null` is absent! +
(No ternary `boolean`.)

=== Getting A Value Out

Many ways to get a value out of an `Optional`. +
All return present value but differ in absence:

* `orElse(T)` returns given default value
* `orElseGet(Supplier<T>)` computes +
default value and returns it
* `orElseThrow()` throws +
`NoSuchElementException` ⑩ +
(in ⑧ & ⑨, use `get()`)
* `orElseThrow(Supplier<X>)` computes +
exception and throws it

=== Getting A Value Out

Canonical example `isPresent()`/`orElseThrow()`:

```java
Optional<String> nameOpt = /* stream pipeline */;
if (nameOpt.isPresent()) {
//  String name = nameOpt.get(); // ⑧ & ⑨
	String name = nameOpt.orElseThrow(); // ⑩+
//  use name
}
```

=== Getting A Value Out

Handling absence less imperatively:

```java
String name;
Optional<String> nameOpt = /* stream pipeline */;
name = nameOpt.orElse("John Doe");
name = nameOpt.orElseGet(this::computeDefaultName);
name = nameOpt.orElseThrow(() ->
	new IllegalStateException("Name should be given."));
```

=== Exercise 1

Imperative use of `Optional`.


== The Functional Way

++++
<table class="toc">
	<tr><td>Optional Basics</td></tr>
	<tr><td>The Imperative Way</td></tr>
	<tr class="toc-current"><td>The Functional Way</td></tr>
	<tr><td>Optionals In Streams</td></tr>
	<tr><td>Summary</td></tr>
</table>
++++

=== The Functional Way

Keep `Optional` around as long as possible +
and use it to process present value.

Like on `Stream`, but eager:

* `filter(Predicate<T>)`
(can make `Optional` empty)
* `map(Function<T, R>)`
* `flatMap(Function<T, Optional<R>>)`
* `ifPresent(Consumer<T>)` (like `Stream::forEach`)
* `ifPresentOrElse​(Consumer<T>, Runnable)` ⑨

=== The Functional Way

```java
User user = /* ... */;
Optional<String> name = /* stream pipeline */;
name
	.filter(this::hasNameDay)
	.map(this::determineNameDay)
	.ifPresent(nameDay -> register(user, nameDay));
```

=== The Functional Way

Or simply continue stream pipeline:

```java
User user = /* ... */;
/* stream pipeline */
	.findAny() // terminal stream operation
	.filter(this::hasNameDay) // on Optional
	.map(this::determineNameDay)
	.ifPresent(nameDay -> register(user, nameDay));
```

=== The Functional Way

Like with streams, +
this doesn't work well +
with checked exceptions.

* use `if`-`isPresent()`-`orElseThrow()` +
to get back to imperative code
* do it as late as possible

=== Getting A Value In

So far:

* `orElse...` help get present value out
* `filter` can remove value

How to recover from empty `Optional`?

With `or(Supplier<Optional<T>>)`. ⑨

=== Getting A value In

```java
public class Search {
	Optional<Customer> inMemory(String id) { /*... */ };
	Optional<Customer> onDisk(String id) { /*... */ };
	Optional<Customer> remotely(String id) { /*... */ };

	Optional<Customer> anywhere(String id) {
		return inMemory(id)
			.or(() -> onDisk(id))
			.or(() -> remotely(id));
	}

}
```

=== Exercise 2

Functional use of `Optional`.


== Optionals In Streams

++++
<table class="toc">
	<tr><td>Optional Basics</td></tr>
	<tr><td>The Imperative Way</td></tr>
	<tr><td>The Functional Way</td></tr>
	<tr class="toc-current"><td>Optionals In Streams</td></tr>
	<tr><td>Summary</td></tr>
</table>
++++

=== Optionals In Streams

What happens if `Optional`-returning method +
is called in a stream pipeline?

```java
private Optional<Customer> findCustomer(String id) {
	// ...
}

Stream<Customer> findCustomers(List<String> ids) {
	return ids.stream()
		.map(this::findCustomer)
		// now we have a Stream<Optional<Customer>>;
		// how do we get to Stream<Customer>?
}
```

=== In Java 8

Filter and map:

```java
Stream<Customer> findCustomers(List<String> ids) {
	return ids.stream()
		.map(this::findCustomer)
		.filter(Optional::isPresent)
		.map(Optional::get) // no orElseThrow() yet
}
```

*Only do this on Java 8!*

=== In Java 9 And Later

To turn an `Optional` into a `Stream` +
of zero or one element(s):

* `Stream<T> stream();` ⑨

=== In Java 9 And Later

Turn into stream and flat-map:

```java
Stream<Customer> findCustomers(List<String> ids) {
	return ids.stream()
		.map(this::findCustomer)
		.flatMap(Optional::stream);
}
```

Alternatively, in one step:

```java
Stream<Customer> findCustomers(List<String> ids) {
	return ids.stream()
		.flatMap(id -> findCustomer(id).stream());
}
```


== Summary

++++
<table class="toc">
	<tr><td>Optional Basics</td></tr>
	<tr><td>The Imperative Way</td></tr>
	<tr><td>The Functional Way</td></tr>
	<tr><td>Optionals In Streams</td></tr>
	<tr class="toc-current"><td>Summary</td></tr>
</table>
++++

=== Summary

* get `Optional` from streams, other APIs +
or create with `of`, `empty`, `ofNullable`
* use like streams with `map`, `flatMap`, `filter`
* process value with `ifPresent`
* get value out with `get`, `orElse...`
