== {title}

{toc}

=== Restrictions

Value classes are immutable and interchangeable, +
which restricts some class-building capabilities.

=== Immutability

Value classes are immutable, +
so all fields are implicitly final.

(Truly final - even to reflection.)

[%step]
But isn't the change from null fields +
to assigned fields a mutation?

=== Recap

Java 25 introduced the early construction phase:

```java
class ComplexNumber extends Number {
	private final double r, i;

	ComplexNumber(double r, double i) {
		this.r = r; // early construction
		this.i = i;
		super(); // transitions early ⇝ late
		LOGGER.log("Created: " + this); // late
	}
}
```

Without `this(...)` or `super(...)`, +
code runs during late construction.

=== Recap

During early construction:

* can write and read fields
* no other access to `this` +
  (e.g. no instance method calls)

⇝ Object can be initialized before other code "sees" it.

=== Value Class Construction

For value classes:

* by default, code runs during early construction
* call to `super(...)` or `this(...)`:
** requires that all fields are set
** is needed to enter late construction

⇝ Initial mutation of final fields can never be observed.

=== Inheritance

Limited superclasses:

> A value class can extend either `java.lang.Object` or an abstract value class, but not an identity class.

No subclasses:

> The class itself is also implicitly final, so it cannot be extended.

=== Business as Usual

Except for the aforementioned restrictions, +
inheritance works as for identity classes:

* inherit from `Object`
* can implement interfaces
* can be abstract

=== Business as Usual

Everything else works as for identity classes, too:

* inherit `equals`, `hashCode`, `toString` from `Object`
* no restriction on the types of fields +
  (value and identity classes both work)

=== Summary

Declaration site restrictions:

* fields and class are final
* can't extends identity classes +
  (except `java.lang.Object`)
* by default, construction code runs +
  during early construction

Everything else works as usual for declaration.

But there are behavioral differences.