== Streams

++++
<table class="toc">
	<tr><td>In APIs</td></tr>
	<tr><td>Exception Handling</td></tr>
	<tr><td>Finding Elements</td></tr>
	<tr><td>Performance</td></tr>
</table>
++++


== Streams

++++
<table class="toc">
	<tr class="toc-current"><td>In APIs</td></tr>
	<tr><td>Exception Handling</td></tr>
	<tr><td>Finding Elements</td></tr>
	<tr><td>Performance</td></tr>
</table>
++++

Using streams in your APIs.

=== Interesting Stream Properties

* streams are unmodifiable
* streams are easy to transform
* streams are lazy

⇝ Good way to enrich data in layers.

=== Enrichment Example

```java
Map<String, User> userById;
Map<String, Address> addrById;

Stream<User> users() {
	return userById.values().stream();
}

Stream<UserAddress> userAddresses() {
	return users()
		.map(user -> UserAddress.of(
				user, addrById.get(user.id())));
}
```

=== Enrichment Example

```java
Map<Address, List<Order>> ordersByAddr;

Stream<Order> ordersFor(UserAdress userAddr) {
	return ordersByAddr
		.get(userAddr.address()).stream();
}

Stream<Delivery> deliveriesFor(UserAdress userAddr) {
	return ordersFor(userAddr)
		.map(order -> Delivery.of(userAddr, order));
}

Stream<Delivery> deliveries() {
	return userAddresses().flatMap(this::deliveriesFor);
}
```

=== Guidelines

* streams can only be traversed once +
⇝ ideally, returned streams can be recreated endlessly
* during traversal collection must not be mutated +
⇝ stick to layers instead of cycles +
(can be harder than it sounds)
* decide carefully where to call `parallel()` +
⇝ close to terminal operation is a good default

=== Accepting Streams

Returning streams is ok.

What about passing them as parameters?

* streams can only be traversed once!
* caller must assume stream is traversed
* works for obvious consumer functions
* possibly a transformed stream can be returned

=== Stream Param Example

```java
// consuming the passed stream
void addUsers(Stream<User> users) {
	users.forEach(this.users::add)
}

// transforming the passed stream
Stream<UserAddress> userAddresses(Stream<User> users) {
	return users
		.map(user -> UserAddress.of(
				user, addrById.get(user.id())));
}
```

=== Reflection On APIs
==== Returning Streams

* returning streams is great +
(unmodifiable but transformable)
* preferably if streams can be recreated
* can be used to gradually enrich data

=== Reflection On APIs
==== Passing Streams

* caller must assume stream is traversed
* works for obvious consumers
* transformations can be hard to track
* never return a traversed stream +
(obvious, right?!)

=== Reflection On APIs
==== But Look Out

* streams can only be traversed once
* no mutation during traversal
* don't make chains too long or +
debuggability suffers


== Streams

++++
<table class="toc">
	<tr><td>In APIs</td></tr>
	<tr class="toc-current"><td>Exception Handling</td></tr>
	<tr><td>Finding Elements</td></tr>
	<tr><td>Performance</td></tr>
</table>
++++

Handling checked exceptions in Streams.

=== Setting the Scene

```java
Stream<User> parse(Stream<String> strings) {
	// compile error:
	// "Unhandled exception ParseException"
	return strings.map(this::parse);
}

User parse(String userString) throws ParseException {
	// ...
}
```

Which options do we have?

=== Try in Lambda

```java
Stream<User> parse(Stream<String> strings) {
	return strings
		.map(string -> { try {
				return parse(string);
			} catch (ParseException ex) {
				return null;
			}})
		.filter(Objects::nonNull);
}
```

* super ugly
* requires extra clean-up step
* handling exception locally can be hard
* troublesome elements "disappear"

=== Try in Method

```java
Stream<User> parse(Stream<String> strings) {
	return strings
			.map(this::tryParse)
			.filter(Objects::nonNull);
}

private User tryParse(String string) {
	try { return parse(string); }
	catch (ParseException ex) { return null; }
}
```

* somewhat ugly
* requires extra clean-up step ("far away")
* handling exception locally can be hard
* troublesome elements "disappear"

=== Sneaky Throws

How to "trick the compiler":

```java
static Function<T, R> hideException(
		CheckedFunction<T, R, Exception> function) {
	return element -> {
		try {
			return function.apply(element);
		} catch (Exception ex) {
			return sneakyThrow(ex);
		}
	};
}

// sneakyThrow does shenanigans with generics
// and unchecked casts to "confuse the compiler"
```

=== Sneaky Throws

```java
Stream<User> parse(Stream<String> strings) {
	return strings
		.map(Util.hideException(this::parse));
}
```

* very surprising (hides a bomb in the stream!)
* stream executor has to handle exception
* can't `try`-`catch(ParseException)` because +
checked exceptions need to be declared
* exception aborts stream pipeline

*Please never do that!*

=== Wrap in Unchecked

Another `Util` method:

```java
static Function<T, R> uncheckException(
		CheckedFunction<T, R, Exception> function) {
	return element -> {
		try {
			return function.apply(element);
		} catch (Exception ex) {
			// add special cases for RuntimeException,
			// InterruptedException, etc.
			throw new IllegalArgumentException(
				element, ex);
		}
	};
}
```

=== Wrap in Unchecked

```java
Stream<User> parse(Stream<String> strings) {
	return strings
		.map(Util.uncheckException(this::parse));
}
```

* stream executor has to handle exception
* exception aborts stream pipeline

=== Remove Trouble

Another `Util` method:

```java
static Function<T, Optional<R>> wrapOptional(
		CheckedFunction<T, R, Exception> function) {
	return element -> {
		try {
			return Optional.of(
				function.apply(element));
		} catch (Exception ex) {
			return Optional.empty();
		}
	};
}
```

=== Remove Trouble

```java
Stream<User> parse(Stream<String> strings) {
	return strings
		.map(Util.wrapOptional(this::parse))
		// Java 9: .flatMap(Optional::stream)
		.filter(Optional::isPresent)
		.map(Optional::get);
}
```

* requires extra clean-up step +
(at least supported by compiler)
* troublesome elements "disappear"

=== Expose With `Try`

`Try<T>` is similar to `Optional`:

* has two states (error or success)
* allows to process them with functions
* parameterized in type of success result

Another `Util` method:

```java
static Function<T, Try<R>> wrapTry(
		CheckedFunction<T, R, Exception> function) {
	return element -> Try.of(
		() -> function.apply(element));
}
```

=== Expose With `Try`

```java
Stream<Try<User>> parse(Stream<String> strings) {
	return strings
		.map(Util.wrapTry(this::parse));
}
```

* requires external library (e.g. http://vavr.io/[Vavr])
* encodes possibility of failure in API
* makes error available to caller
* error is encoded as Exception/Throwable

=== Expose With `Either`

`Either<L, R>` is similar to `Optional`:

* has two states (left or right)
* allows to process them with functions
* parameterized in types of left and right
* if used for failure/success, exception goes left +
(by convention)

=== Expose With `Either`

Another `Util` method:

```java
static Function<T, Either<EX, R>> wrapEither(
		CheckedFunction<T, R, EX> function) {
	return element -> {
		try {
			return Either.right(
				function.apply(element));
		} catch (Exception ex) {
			// add special cases for RuntimeException,
			// InterruptedException, etc.
			return Either.left((EX) ex);
		}
	};
}
```

=== Expose With `Either`

```java
Stream<Either<ParseException, User>> parse(
		Stream<String> strings) {
	return strings
		.map(Util.wrapEither(this::parse));
}
```

* requires external library (e.g. http://vavr.io/[Vavr])
* encodes possibility of failure in API
* makes error available to caller
* error has correct type

=== Reflection on Exceptions

* don't be smart and "trick the compiler"
* return a clean stream, no `null`!
* ideally, use types to express possibility of failure

Streams don't cooperate well with checked exceptions.

See that as a chance to use functional concepts +
for greater good of code base!

== Streams

++++
<table class="toc">
	<tr><td>In APIs</td></tr>
	<tr><td>Exception Handling</td></tr>
	<tr class="toc-current"><td>Finding Elements</td></tr>
	<tr><td>Performance</td></tr>
</table>
++++

Be careful how you find!

=== Finding First or Any

`Stream::findFirst` and `findAny`:

* return an arbitrary element from the Stream
* if stream has encounter order, +
`findFirst` returns first element

Often used after a filter.

=== Find Example

```java
Optional<User> findUser(String id) {
	return users.stream()
		.filter(user -> user.id().equals(id))
		.findFirst();
}
```

Same as the loop:

```java
Optional<User> findUser(String id) {
	for (User user : users)
		if (user.id().equals(id))
			return Optional.of(user);
	return Optional.empty();
}
```

=== Small Observation

I sometimes see the following:

* code's correctness depends on only +
one element passing the filter
* *but* there are no additional checks

*⇝ The easy solution might be the wrong one!*

[role="small-note"]
(Applies to the loop as well.)

=== Finding Only

Make sure there is only one element:

```java
Optional<User> findUser(String id) {
	return users.stream()
		.filter(user -> user.id().equals(id))
		.reduce(toOnlyElement());
}

static BinaryOperator toOnlyElement() {
	return (element, otherElement) -> {
		throw new IllegalArgumentException();
	};
}
```

(`Stream::collect` is an alternative to `reduce`.)

=== Properties of Finding Only

Upsides:

* guarantees correctness by failing fast
* expresses intent

Downsides:

* materializes entire stream

=== Reflection On Finding

If correctness depends on only one element +
surviving an ad-hoc filter:

* `findFirst`, `findAny` do not suffice
* use a reducer or collector to assert uniqueness
* comes with a performance penalty

==== Additional Sources

http://blog.codefx.org/java/stream-findfirst-findany-reduce/[Beware Of findFirst() And findAny()]


== Stream

++++
<table class="toc">
	<tr><td>In APIs</td></tr>
	<tr><td>Exception Handling</td></tr>
	<tr><td>Finding Elements</td></tr>
	<tr class="toc-current"><td>Performance</td></tr>
</table>
++++

Getting a gut feeling

=== Performance Caveat

Don't get carried away with performance!

Before optimizing loops vs streams:

* gather performance requirements
* reliably measure performance
* act when requirements are not met
* determine that stream is at fault

=== Performance Caveat

Performance measurements are hard +
and I'm not good at them!

* https://blog.codefx.org/java/stream-performance/[concrete numbers] apply only to my setup
* focus on how they relate
* even that differs across setups

If it's important, benchmark yourself!

Use https://openjdk.java.net/projects/code-tools/jmh/[JMH] for that.

=== Stream Performance

Simple benchmark: +
find max in `int[500_000]`

```java
// takes 0.123
int m = Integer.MIN_VALUE;
for (int i = 0; i < intArray.length; i++)
	if (intArray[i] > m)
		m = intArray[i];

// takes 0.599
Arrays.stream(intArray).max();
```

20% performance ⇝ streams suck 😱

=== Really, though?

Couple of things to note:

* are 500'000 elements few or many? +
  ⇝ vary number of elements
* finding max is really cheap! +
  ⇝ try other operations
* arrays are rare; lists more common +
  ⇝ use different collections

Let's vary things a little.

=== Data structures

Throw a `List<Integer>` into the mix:

[%header]
|===
| iteration | array | list
| for	    | 0.123 | 0.700
| stream    | 0.599 | 3.272
|===

⇝ That didn't change much...

=== Cost Per Operation

Benchmark more operations:

* _max_: finding the maximum
* _sum_: summing `int` (ignoring overflows)
* _arithmetic_: handful of bit shifts and mults
* _string_: convert to string, xor char by char

=== Cost Per Operation

*--- Array ---*

[%header]
|===
| iteration | max   | sum   | arith   | string
| for	    | 0.123 | 0.186 | 4.405   | 49.533
| stream    | 0.599 | 1.394 | 4.100   | 52.236
|===

*--- List ---*

[%header]
|===
| iteration | max   | sum    | arith   | string
| for	    | 0.700 | 0.714  | 4.099   | 49.943
| stream    | 3.272 | 3.584  | 7.776   | 64.989
|===

=== Cost Per Operation

Define `Q` as abstract cost of operation:

* _max_ and _sum_ are very cheap
* _arithmetic_ is x3 to x20
* _string_ is another x10

⇝ Reasonably complex operations +
dominate total run time.

=== Number Of Elements

From 500'000 to 50'000'000 elements:

[%header]
|===
| structure | op    | iteration | speedup
| array     | _sum_ | stream    | x6.62
| list      | _max_ | stream    | x1.16
| list      | _sum_ | stream    | x1.08
| list      | _max_ | for       | x0.89
| array     | _sum_ | for       | x0.88
| array     | _max_ | for	    | x0.7
|===

=== Number Of Elements

Define `N` as number of elements.

For larger `N`, these speed up:

* more complex iteration mechanisms
* over simple operations

⇝ This benefits streams.

=== Taken together

Streams are always slower than loops, but:

* doesn't matter if `N*Q` is small
* gets better the larger `N*Q` gets
* asymptotically approaching x1

*⇝ Unless specific perf reqs are in the way, +
streams are a good default.*

Streams are easy to parallelize...

=== Parallel Performance

Parallelization adds overhead:

* decomposing the problem
* task / thread management
* composing the result

Only benefit: more resources!

(May be limited by memory bandwidth.)

=== Parallel Performance

Super simplified model +
(remember `N` and `Q`):

*`N*Q` should be five digits (at least)*

⇝ Parallel streams are no good default!

=== Parallel Performance

For details on parallel performance:

https://www.youtube.com/watch?v=iDplU7mOocU&t=25m20s[Thinking in Parallel] +
by Stuart Marks and Brian Goetz at JavaOne 2016 +
(start at 25:20 for performance)

++++
<iframe width="560" height="315" src="https://www.youtube.com/embed/2nup6Oizpcw" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
++++

=== Reflection on Performance

* stream overhead is real +
  but almost disappears for relevant sizes
* performance is rarely a reason against streams
* consider parallel streams carefully
* measure and compare to requirements!
