== Data-Oriented Programming

++++
<table class="toc">
	<tr><td>What is DOP?</td></tr>
	<tr><td>A Lengthy Example</td></tr>
	<tr class="toc-current"><td>That was DOP!</td></tr>
</table>
++++

=== Dynamic dispatch

Dynamic dispatch selects the invoked method by type.

As language feature:

* via inheritance
* makes method part of API

What if methods shouldn't be part of the API?

=== Dynamic dispatch

Without methods becoming part of the API.

Via visitor pattern:

* makes "visitation" part of API
* cumbersome and indirect

=== Dynamic dispatch

Without methods becoming part of the API.

Via pattern matching (new):

* makes "sealed" part of type
* straight-forward

=== Patterns and language

Design patterns make up gaps in the language.

Good example is the strategy pattern:

* used to be "a thing" in Java
* you use it everytime you pass a lambda

But do you still think of it a design pattern? +
(I don't.)

Pattern matching does the same for the visitor pattern.

=== Applications

* ad-hoc data structures
* complex return types
* complex domains

=== Ad-hoc Data Structures

Often local, throw-away types used in one class or package.

```java
record PageWithLinks(Page page, Set<URI> links) {

	PageWithLinks {
		requireNonNull(page);
		requireNonNull(links);
		links = new HashSet<>(links);
	}

	public PageWithLinks(Page page) {
		this(page, Set.of());
	}

}
```

=== Complex Return Types

Return values that are deconstructed immediately:

```java
// type declaration
sealed interface Match<T> { }

record None<T>() implements Match<T> { }
record Exact<T>(T entity) implements Match<T> { }
record Fuzzies<T>(Collection<Fuzzy<T>> entities)
	implements Match<T> { }

record Fuzzy<T>(T entity, int distance) { }

// method declaration
Match<User> findUser(String userName) { ... }
```

=== Complex Return Types

Return values that are deconstructed immediately:

```java
// calling the method
switch (findUser("John Doe")) {
	case None<> none -> // ...
	case Exact<> exact -> // ...
	case Fuzzies<> fuzzies -> // ...
}
```

=== Complex Domains

Long-living objects that are part +
of the program's domain.

For example `Page`.

=== Algebraic Data Types

* records are _product types_
* sealed types are _sum types_

> This simple combination of mechanisms -- aggregation and choice -- is deceptively powerful

=== Functional Programming?!

* immutable data structures
* methods (functions?) that operate on them

Isn't this just functional programming?!

[%step]
Kind of.

=== DOP vs FP

**Functional programming:**

> Everything is a function

⇝ Focus on creating and composing functions.

---

**Data-oriented programming:**

> Model data as data.

⇝ Focus on correctly modeling the data.

////
Brian:

At a superficial level, X-oriented programming says "everything is an X"
So functional programming focuses on functions, composing functions, etc.  Everything is a function.
No real distinction between "data" and functions, they're all values.

DOP says "its all about the data".  The programming model is driven by the data; the business logic is secondary.
obviously you can program without either behavior or data

but its where you put the programmers attention
is it object modeling?  is it factoring the computation so it can be composed functionally?  is it data modeling?
////

=== DOP vs OOP

**OOP is not dead (again):**

* valuable for complex entities or rich libraries
* use whenever encapsulation is needed
* still a good default on high level

**DOP --  consider when:**

* mainly handling outside data
* working with simple or ad-hoc data
* data and behavior should be separated

=== Data-Oriented Programming

Use Java's strong typing to model data as data:

* use classes to represent data, particularly:
** data as data with records
** alternatives with sealed classes
* use methods (separately) to model behavior, particularly:
** exhaustive `switch` without `default`
** pattern matching to destructure polymorphic data

=== More

More on pattern matching:

* 📝 https://www.infoq.com/articles/data-oriented-programming-java/[Data Oriented Programming in Java]
* 🎥 https://www.youtube.com/watch?v=QrwFrm1R8OY[Java 21 Brings Full Pattern Matching]
* 🎥 https://www.youtube.com/watch?v=5qYJYGvVLg8[Data-Oriented Programming]
* 📝 https://openjdk.org/projects/amber/design-notes/patterns/pattern-match-object-model[Pattern Matching in the Java Object Model]
* 🧑‍💻 https://github.com/nipafx/loom-lab[GitHub crawler]
