== {title}

{toc}

// Plug in host name and address resolution.

=== Built-in resolver

The JDK has a built-in resolver for host names:

* relies on OS's native resolver
* typically uses `hosts` file and DNS

Desirable improvements:

* better interaction with virtual threads
* support for alternative protocols
* support for testing/mocking

(While being backwards compatible.)

=== Pluggable resolver

*Solution*: Allow plugging in a custom resolver.

Two new types:

* `InetAddressResolverProvider`
* `InetAddressResolver`

Old resolver implements these, +
and acts as default.

=== Pluggable resolver

```java
// registered as a service
public abstract class InetAddressResolverProvider {
	InetAddressResolver get(Configuration config);
	String name();
}

public interface InetAddressResolver {
	Stream<InetAddress> lookupByName(
		String host, LookupPolicy lookupPolicy);
	String lookupByAddress(byte[] addr);
}
```

=== A transparent custom resolver

```java
// in module declaration
provides InetAddressResolverProvider
	with TransparentInetAddressResolverProvider;

// class
public class TransparentInetAddressResolverProvider
		extends InetAddressResolverProvider {

	@Override
	public InetAddressResolver get(
			Configuration config) {
		return new TransparentInetAddressResolver(
			config.builtinResolver());
	}

}
```

=== A transparent custom resolver

```java
public class TransparentInetAddressResolver
		implements InetAddressResolver {

	private InetAddressResolver builtinResolver;

	public TransparentInetAddressResolver(
			InetAddressResolver builtinResolver) {
		this.builtinResolver = builtinResolver;
	}

	// ...

}
```

=== A transparent custom resolver

```java
@Override
public Stream<InetAddress> lookupByName(
		String host, LookupPolicy lookupPolicy) {
	return builtinResolver
		.lookupByName(host, lookupPolicy);
}

@Override
public String lookupByAddress(byte[] addr) {
	return builtinResolver.lookupByAddress(addr);
}
```

=== Custom resolvers

Possible resolvers:

* support for QUIC, TLS, HTTPS, etc.
* redirect host names to local IPs for testing
* more ideas?

=== More

📝 https://openjdk.org/jeps/418[JEP 418]
