== {title}

{toc}

Asynchronous error recovery.

=== Recap on API Basics

```java
// start an asynchronous computation
public static CompletableFuture<T> supplyAsync(
	Supplier<T>);

// attach further steps
public CompletableFuture<U> thenApply(Function<T, U>);
public CompletableFuture<U> thenCompose(
	Function<T, CompletableFuture<U>);
public CompletableFuture<Void> thenAccept(Consumer<T>);

// wait for the computation to finish and get result
public T join();
```

=== Recap on API Basics

Example:

```java
public void loadWebPage() {
	String url = "https://nipafx.dev";
	CompletableFuture<WebPage> future = CompletableFuture
			.supplyAsync(() -> webRequest(url))
			.thenApply(html -> new WebPage(url, html));
	// ... do other stuff
	WebPage page = future.join();
}

private String webRequest(String url) {
	// make request to URL and return HTML
	// (this can take a while)
}
```

=== Recap on Completion

A pipeline or stage _completes_ when +
the underlying computation terminates.

* it _completes normally_ if +
  the computation yields a result
* it _completes exceptionally_ if +
  the computation results in an exception

=== Recap on Error Recovery

Two methods to recover errors:

```java
// turn the error into a result
CompletableFuture<T> exceptionally(Function<Throwable, T>);
// turn the result or error into a new result
CompletableFuture<U> handle(BiFunction<T, Throwable, U>);
```

They turn _exceptional completion_ of the previous stage +
into _normal completion_ of the new stage.

=== Recap on Error Recovery

Example:

```java
loadUser(id)
	.thenCompose(this::loadUserHistory)
	.thenCompose(this::createRecommendations)
	.exceptionally(ex -> {
		log.warn("Recommendation error", ex)
		return createDefaultRecommendations();
	})
	.thenAccept(this::respondWithRecommendations);
```

=== Composeable Error Recovery ⑫

Error recovery accepts functions +
that produce `CompletableFuture`:

```java
exceptionallyCompose(
	Function<Throwable, CompletionStage<T>>)
```

=== Recap on (A)Synchronicity

Which threads actually compute the stages?

* `supplyAsync(Supplier<T>)` is executed +
  in the https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ForkJoinPool.html#commonPool--[common fork/join pool]
* for other stages it's undefined:
** could be the same thread as the previous stage
** could be another thread in the pool
** could be the thread calling `thenAccept` et al.

How to force async computation?

=== Recap on (A)Synchronicity

All "composing" methods +
have an `...Async` companion, e.g.:

```java
thenApplyAsync(Function<T, U>);
thenAcceptAsync(Consumer<T>);
```

They submit each stage as a separate task +
to the common fork/join pool.

=== Async Error Recovery ⑫

Error recovery can be asynchronous:

```java
CompletableFuture<T> exceptionallyAsync(
	Function<Throwable, T>)
CompletableFuture<T> exceptionallyComposeAsync(
	Function<Throwable, CompletableFuture<T>>)
```

There are overloads that accept `Executor`.
