== {title}

{toc}

=== PEM texts

Representations of cryptographic objects +
(keys, certificates, certificate revocation lists):

```
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj
0DAQcDQgAEi/kRGOL7wCPTN4KJ
2ppeSt5UYB6ucPjjuKDtFTXbgu
OIFDdZ65O/8HTUqS/sVzRF+dg7
H3/tkQ/36KdtuADbwQ==
-----END PUBLIC KEY-----
```

=== Privacy-enhanced... mail?!

Was introduced for exchange via email +
but moved way beyond:

* development platforms (e.g. GitHub)
* certificate authorities
* cryptographic libraries (e.g. OpenSSL)
* security-sensitive applications (e.g. OpenSSL)
* hardware authentication devices (e.g. YubiKeys)
* your applications

⇝ Very helpful if Java handled them.

=== Manual En-/Decoding

To *encode*:

* create binary representation of object
* Base64-encode it
* surround string with `BEGIN`/`END` lines

To *decode*: reverse that.

⇝ Java has all the building blocks, but +
combining them is cumbersome.


=== PEM API

New PEM API is straightforward to use:

```java
X509Certificate cert = // ...

// encode
PEMEncoder encoder = PEMEncoder.of();
String pem = encoder.encodeToString(cert);

// decode
PEMDecoder decoder = PEMDecoder.of();
DEREncodable cert2 = decoder.decode(pem);

assert cert.equals(cert2);
```

=== Endcoder/Decoder

Instances of `PEMEncoder` and `PEMDecoder` are:

* immutable
* thread-safe 
* reusable

=== Encodable

All implementations of `DEREncodable` can be encoded:

* `AsymmetricKey` +
  (DH, DSA, EC, RSA, etc.)
* `KeyPair`
* `PKCS8EncodedKeySpec`
* `X509EncodedKeySpec`
* `X509Certificate`
* `X509CRL`
* `EncryptedPrivateKeyInfo`
* `PEM`

=== Decoding

For decoding:

* if the object type is known, call +
  `decode(String, Class<T extends DEREncodable>)`:
+
```java
KeyPair kp = decoder.decode(pem, KeyPair.class);
```
* otherwise, `switch`/`instanceof` over +
  return value of `decode(String)` 

(Overloads for `InputStream` exist.)

=== Unknown objects

Unknown cryptographic objects are decoded to `PEM`:

* `String type` (header text)
* `String content` (Base64-encoded body)
* `byte[] leadingData` (data preceding the header)

=== Encryption

`PrivateKey`, `KeyPair`, `PKCS8EncodedKeySpec` +
instances can be encrypted/decrypted:

```java
PrivateKey key = // ...
char[] pass = // ...

String pem = encoder
	.withEncryption(pass)
	.encodeToString(key);
DEREncodable der = decoder
	.withDecryption(pass)
	.decode(pem);
```

(Custom parameters/providers can be configured.)

=== More

Second preview in JDK 26.

* 📝 https://openjdk.org/jeps/524[JEP 524]: PEM Encodings of Cryptographic Objects
* 🎥 https://www.youtube.com/watch?v=hqvMn2SwKiI[Java 25 Encodes PEM]
