== Java 21 💣💥

{toc}

=== Collections

How do you create an `ArrayList` that +
can store 50 elements without resizing?

[step=1]
```java
new ArrayList<>(50);
```

[step=2]
How do you create a `HashMap` that +
can store 50 pairs without resizing?

[step=3]
```java
new HashMap<>(64, 0.8f);
new HashMap<>(128);
```

[step=3]
🤔

=== Collections

Right-sizing hashing data structures:

* `HashMap.newHashMap(int numMappings)`
* `HashSet.newHashSet(int numElements)`
* `LinkedHashMap.newLinkedHashMap(int numMappings)`
* `LinkedHashSet.newLinkedHashSet(int numElements)`

=== Math

Lots of new methods on `Math`:

* for `int`/`long` division with different modes for:
** rounding
** overflow handling
* for ceiling modulus (`5 ⌈%⌉ 3 = -1`)
* for clamping

=== Strings and builders

```java
"String".indexOf(
	String str, int beginIndex, int endIndex)
```

On `StringBuilder` and `StringBuffer`:

* `repeat(int codePoint, int count)`
* `repeat(CharSequence cs, int count)`

=== 💣💥

On `Character` (all `static`):

* `isEmoji(int codePoint)`
* `isEmojiPresentation(int codePoint)`
* `isEmojiModifier(int codePoint)`
* `isEmojiModifierBase(int codePoint)`
* `isEmojiComponent(int codePoint)`

=== Localizing DateTimes

Options for formatting dates/times with `DateTimeFormatter`:

* with a fixed pattern: `ofPattern`
* with a localized style: `ofLocalizedDate` +
  (`FULL`, `LONG`, `MEDIUM`, `SHORT`)

What about a localized result with custom elements?

⇝ `DateTimeFormatter.ofLocalizedPattern`

=== Localized patterns

`DateTimeFormatter.ofLocalizedPattern`:

* you include what you want to show up +
  (e.g. year + month with `"yMM"`)
* result will depend on locale +
  (e.g. `"10/2023"` in USA)

=== Pattern comparison:

```java
var now = ZonedDateTime.now();
for (var locale : List.of(
		Locale.of("en", "US"),
		Locale.of("be", "BE"),
		Locale.of("vi", "VN"))) {
	Locale.setDefault(locale);

	var custom = DateTimeFormatter
		.ofPattern("y-MM-dd");
	var local = DateTimeFormatter
		.ofLocalizedDate(FormatStyle.SHORT);
	var customLocal = DateTimeFormatter
		.ofLocalizedPattern("yMM");

	// pretty print
}
```

=== Pattern comparison

[%header,cols="6,10,10,12"]
|===
| locale |   custom   |  local     |   both
| en_US  | `2023-10-02` | `10/2/23`    | `10/2023`
| be_BE  | `2023-10-02` | `2.10.23`    | `10.2023`
| vi_VN  | `2023-10-02` | `02/10/2023` | `tháng 10, 2023`
|===

=== Localized patterns

Analogue methods were added to `DateTimeFormatterBuilder`:

```java
DateTimeFormatterBuilder appendLocalized(
	String requestedTemplate);

static String getLocalizedDateTimePattern(
	String requestedTemplate,
	Chronology chrono, Locale locale)
```

=== More AutoCloseable

These types now implemnet `AutoCloseable`:

* `HttpClient`
* `ExecutorService`
* `ForkJoinPool`

=== A better future

Additions to `Future<T>`:

* `T resultNow()`
* `Throwable exceptionNow`
* `State state()`

New:

```java
enum State {
	RUNNING, SUCCESS, FAILED, CANCELLED
}
```

=== More

There are many more additions like this.

Find a few more in +
🎥 https://www.youtube.com/watch?v=4mPd2eL0wYQ[Java 21 API New Features] (Sep 2023)
