== New Language Features

++++
<table class="toc">
	<tr><td>Local-Variable Type Inference ⑩</td></tr>
	<tr><td>Private Interface Methods ⑨</td></tr>
	<tr><td>Try-With-Resources ⑨</td></tr>
	<tr><td>Diamond Operator ⑨</td></tr>
	<tr><td>SafeVarargs ⑨</td></tr>
	<tr><td>Deprecation Warnings ⑨</td></tr>
</table>
++++

// === Sneak Preview
//
// Java 12 `switch` expressions:
//
// ```java
// public void switchExpression() {
// 	var bool = Bool.random();
// 	boolean result = switch (bool) {
// 		case TRUE -> true;
// 		case FALSE -> false;
// 		case FILE_NOT_FOUND ->
// 			throw new UncheckedIOException(
// 				"This is ridiculous!",
// 				new FileNotFoundException());
// 	};
// }
// ```


== New Language Features

++++
<table class="toc">
	<tr class="toc-current"><td>Local-Variable Type Inference ⑩</td></tr>
	<tr><td>Private Interface Methods ⑨</td></tr>
	<tr><td>Try-With-Resources ⑨</td></tr>
	<tr><td>Diamond Operator ⑨</td></tr>
	<tr><td>SafeVarargs ⑨</td></tr>
	<tr><td>Deprecation Warnings ⑨</td></tr>
</table>
++++

Type inference with `var`. +
Less typing, but still strongly typed.


=== Type Duplication

We're used to duplicating +
type information:

```java
URL codefx = new URL("http://codefx.org");
URLConnection connection = codefx.openConnection();
Reader reader = new BufferedReader(
	new InputStreamReader(
		connection.getInputStream()));
```

Not so bad?

=== Type Duplication

What about this?

```java
No no = new No();
AmountIncrease<BigDecimal> more =
	new BigDecimalAmountIncrease();
HorizontalConnection<LinePosition, LinePosition>
	jumping =
		new HorizontalLinePositionConnection();
Variable variable = new Constant(5);
List<String> names = List.of("Max", "Maria");
```

=== Type Deduplication

Can't somebody else do that? +
Compiler knows the types!

Enter `var`:

```java
var codefx = new URL("http://codefx.org");
var connection = codefx.openConnection();
var reader = new BufferedReader(
	new InputStreamReader(
		connection.getInputStream()));
```

=== Locality

How much information is used for inference?

* type inference can be +
  arbitrarily complex/powerful
* critical resource is not +
  compiler but developer
* code should be readable +
  (without compiler/IDE)

⇝ Better to keep it simple!

=== "Action at a distance"

```java
// inferred as `int`
var id = 123;
if (id < 100) {
	// very long branch
} else {
	// oh boy, much more code...
}

// now we add this line:
id = "124";
```

What type should `id` be?

Where does the error show up?

=== Rules of `var`

Hence, `var` only works in limited scopes:

[%step]
* compiler infers type from right-hand side +
  ⇝ rhs has to *exist* and *define a type*
* only works for local variables, `for`, `try` +
  ⇝ no `var` on fields or in method signatures
* also on lambda parameters ⑪ +
  ⇝ annotate inferred type on lambda parameters

=== Rules of `var`

Two more:

* not a keyword, but a _reserved type name_ +
  ⇝ variables/fields can be named `var`
* compiler writes type into bytecode +
  ⇝ no run-time component

=== What About Readability?

This *is* about readability!

* less redundancy
* more intermediate variables
* more focus on variable names
* aligned variable names

=== Aligned Variable Names

```java
var no = new No();
var more = new BigDecimalAmountIncrease();
var jumping = new HorizontalLinePositionConnection();
var variable = new Constant(5);
var names = List.of("Max", "Maria");
```

=== What About Readability?

Still think omitting types is always bad?

Ever wrote a lambda without declaring types?

```java
rhetoricalQuestion.answer(yes -> "see my point?");
```

=== Style Guidelines

Principles from the
http://openjdk.java.net/projects/amber/LVTIstyle.html[official style guidelines]:

[%step]
. Reading code is more important than writing it.
. Code should be clear from local reasoning.
. Code readability shouldn't depend on IDEs.
. Explicit types are a tradeoff.

=== Style Guidelines

Guidelines:

[%step]
. Choose variable names that provide useful info.
. Minimize the scope of local variables.
. Consider `var` when the initializer provides sufficient information to the reader.
. Use `var` to break up chained or nested expressions.
. Don't worry too much about "programming to the interface".
. Take care when using `var` with diamonds or generics.
. Take care when using `var` with literals.

=== More on `var`

* First Contact With `var` In Java 10 +
💻 https://blog.codefx.org/java/java-10-var-type-inference/[tiny.cc/java-var] /
▶ https://www.youtube.com/watch?v=Le1DbpRZdRQ&index=1&list=PL_-IO8LOLuNp2stY1qBUtXlfMdJW7wvfT[tiny.cc/java-var-yt]
* https://snyk.io/blog/local-type-inference-java-cheat-sheet[cheat sheet] (*⇜ print when getting started!*)
* http://openjdk.java.net/projects/amber/LVTIstyle.html[official style guidelines]
* `var` and ...
** https://blog.codefx.org/java/intersection-types-var/[intersection types]
** https://blog.codefx.org/java/traits-var/[traits]
** https://blog.codefx.org/java/tricks-var-anonymous-classes/[anonymous classes]



== New Language Features

++++
<table class="toc">
	<tr><td>Local-Variable Type Inference ⑩</td></tr>
	<tr class="toc-current"><td>Private Interface Methods ⑨</td></tr>
	<tr><td>Try-With-Resources ⑨</td></tr>
	<tr><td>Diamond Operator ⑨</td></tr>
	<tr><td>SafeVarargs ⑨</td></tr>
	<tr><td>Deprecation Warnings ⑨</td></tr>
</table>
++++

Enabling reuse between default methods.

=== No Reuse

```java
public interface InJava8 {

	default boolean evenSum(int... numbers) {
		return sum(numbers) % 2 == 0;
	}

	default boolean oddSum(int... numbers) {
		return sum(numbers) % 2 == 1;
	}

	default int sum(int[] numbers) {
		return IntStream.of(numbers).sum();
	}

}
```

=== Private Methods

```java
public interface InJava9 {

	private int sum(int[] numbers) {
		return IntStream.of(numbers).sum();
	}

}
```

Just like private methods in abstract classes:

* must be implemented
* can not be overriden
* can only be called in same source file



== New Language Features

++++
<table class="toc">
	<tr><td>Local-Variable Type Inference ⑩</td></tr>
	<tr><td>Private Interface Methods ⑨</td></tr>
	<tr class="toc-current"><td>Try-With-Resources ⑨</td></tr>
	<tr><td>Diamond Operator ⑨</td></tr>
	<tr><td>SafeVarargs ⑨</td></tr>
	<tr><td>Deprecation Warnings ⑨</td></tr>
</table>
++++

Making `try`-with-resources blocks cleaner.

=== Useless Variable

```java
void doSomethingWith(Connection connection)
		throws Exception {
	try(Connection c = connection) {
		c.doSomething();
	}
}
```

Why is `c` necessary?

=== Why is `c` necessary?

* target of `close()` must be obvious +
⇝ resource should not be reassigned
* easiest if resource is final
* easiest if resource must be assigned +
and can be made implicitly final

```java
try(Connection c = connection)
```

=== Effectively Final Resource

But since Java 8 we have _effectively final_!

This works in Java 9:

```java
void doSomethingWith(Connection connection)
		throws Exception {
	try(connection) {
		connection.doSomething();
	}
}

```

* compiler knows that `connection` is not reassigned
* developers know what _effectively final_ means

[NOTE.speaker]
--
Q: Can instance be created but not assigned? No.
--


== New Language Features

++++
<table class="toc">
	<tr><td>Local-Variable Type Inference ⑩</td></tr>
	<tr><td>Private Interface Methods ⑨</td></tr>
	<tr><td>Try-With-Resources ⑨</td></tr>
	<tr class="toc-current"><td>Diamond Operator ⑨</td></tr>
	<tr><td>SafeVarargs ⑨</td></tr>
	<tr><td>Deprecation Warnings ⑨</td></tr>
</table>
++++

A little more type inference.

=== Diamond Operator

Maybe the best example:

```java
List<String> strings = new ArrayList<>();
```

* used at a constructor call
* tells Java to infer the parametric type


=== Anonymous Classes

Diamond did not work with anonymous classes:

```java
<T> Box<T> createBox(T content) {
	// we have to put the `T` here :(
	return new Box<T>(content) { };
}
```

Reason are non-denotable types:

* might be inferred by compiler +
  for anonymous classes
* can not be expressed by JVM

=== Infer Denotable Types

Java 9 infers denotable types:

```java
<T> Box<T> createBox(T content) {
	return new Box<>(content) { };
}
```

Gives compile error if type is non-denotable:

```java
Box<?> createCrazyBox(Object content) {
	List<?> innerList = Arrays.asList(content);
	// compile error
	return new Box<>(innerList) { };
}
```



== New Language Features

++++
<table class="toc">
	<tr><td>Local-Variable Type Inference ⑩</td></tr>
	<tr><td>Private Interface Methods ⑨</td></tr>
	<tr><td>Try-With-Resources ⑨</td></tr>
	<tr><td>Diamond Operator ⑨</td></tr>
	<tr class="toc-current"><td>SafeVarargs ⑨</td></tr>
	<tr><td>Deprecation Warnings ⑨</td></tr>
</table>
++++

One less warning you couldn't do anything about.

=== Heap Pollution

Innocent looking code...

```java
private <T> Optional<T> firstNonNull(T... args) {
	return stream(args)
			.filter(Objects::nonNull)
			.findFirst();
}
```

Compiler warns (on call site, too):

```
Possible heap pollution from
parameterized vararg type
```

=== Heap Pollution?

For generic varargs argument `T... args`, +
you *must not* depend on it being a `T[]`!

```java
private <T> T[] replaceTwoNulls(
		T value, T first, T second) {
	return replaceAllNulls(value, first, second);
}

private <T> T[] replaceAllNulls(T value, T... args) {
	// loop over `args`, replacing `null` with `value`
	return args;
}
```

=== Compiler Warning

Compiler is aware of the problem and warns you.

If you think, everything's under control:

```java
@SafeVarargs
private <T> Optional<T> firstNonNull(T... args) {
	return // [...]
}
```

Or not... In Java 8 this is a compile error!

```
Invalid SafeVarargs annotation. Instance
method <T>firstNonNull(T...) is not final.
```

=== But Why?

The `@SafeVarargs` annotation:

* tells _the caller_ that all is fine
* only makes sense on methods +
that can not be overriden

Which methods can't be overriden? +
⇝ `final` methods

What about `private` methods? +
⇝ Damn! 😭

=== @SafeVarargs on Private&nbsp;Methods

Looong story, here's the point:

In Java 9 `@SafeVarargs` +
can be applied to private methods.



== New Language Features

++++
<table class="toc">
	<tr><td>Local-Variable Type Inference ⑩</td></tr>
	<tr><td>Private Interface Methods ⑨</td></tr>
	<tr><td>Try-With-Resources ⑨</td></tr>
	<tr><td>Diamond Operator ⑨</td></tr>
	<tr><td>SafeVarargs ⑨</td></tr>
	<tr class="toc-current"><td>Deprecation Warnings ⑨</td></tr>
</table>
++++

_Another_ warning you couldn't do anything about.

=== Deprecation Warnings

Should this code emit a warning?

++++
<div style="height: 350px;">
<div class="listingblock fragment current-display"><div class="content"><pre class="highlight"><code class="java language-java hljs">// LineNumberInputStream is deprecated
<span class="hljs-keyword">import</span> java.io.LineNumberInputStream;


<span class="hljs-keyword">public</span> <span class="hljs-class"><span class="hljs-keyword">class</span> <span class="hljs-title">DeprecatedImports</span> </span>{

    LineNumberInputStream stream;

}</code></pre></div></div>
<div class="listingblock fragment current-display"><div class="content"><pre class="highlight"><code class="java language-java hljs">// LineNumberInputStream is deprecated
<span class="hljs-keyword">import</span> java.io.LineNumberInputStream;

<span class="hljs-meta">@Deprecated</span>
<span class="hljs-keyword">public</span> <span class="hljs-class"><span class="hljs-keyword">class</span> <span class="hljs-title">DeprecatedImports</span> </span>{

    LineNumberInputStream stream;

}</code></pre></div></div></div>
++++

=== Not On Imports

Java 9 no longer emits warnings +
for importing deprecated members.

Warning free:

```java
import java.io.LineNumberInputStream;

@Deprecated
public class DeprecatedImports {

	LineNumberInputStream stream;

}
```
