== {title}

{toc}

// A quality-of-life improvement.

=== Constructor Chaining

With multiple constructors, +
it's good practice to have one constructor that:

* checks all arguments
* assigns all fields

Other constructors just forward (if possible).

=== Constructor Chaining

```java
class Name {

	protected final String first, last;

	Name(String first, String last) {
		// [... checks, assignments, etc. ...]
	}

	Name(String fst, String mid, String lst) {
		this(fst + " " + mid, lst);
	}
}

```

=== Inheritance

With superclasses, chaining is enforced:

```java
class ThreePartName extends Name {

	protected final String middle;

	ThreePartName(String fst, String mid, String lst) {
		// doesn't compile without this call
		super(fst, lst);
		this.middle = mid;
	}
}
```

=== Limitations

**But**:

* superclass should be initialized +
  before subclass runs any code +
  ⇝ no code before `super(...)`
* code before `this(...)` would +
  run before `super(...)` +
  ⇝ no code before `this(...)`

So: no statements before `super(...)` / `this(...)`!

=== Consequence

With:

* `class A`
* `class B extends A`
* `class C extends B`

Effective constructor execution for `new C()`:

`Object` ⇝ `A` ⇝ `B` ⇝ `C`

=== Irregularities

```java
Name(String first, String last) {
	this.first = first;
	this.last = last;
	IO.println(this);
}

ThreePartName(String fst, String mid, String lst) {
	super(fst, lst);
	this.middle = mid;
}

new ThreePartName("Jane", "Jennifer", "Doe");
// prints: "Jane null Doe" 😖
```

=== Inconveniences

Limitation is inconvenient when you want to:

* check arguments
* prepare arguments
* split/share arguments

=== Splitting Arguments

```java
class Name {

	protected final String first;
	protected final String last;

	Name(String first, String last) {
		this.first = first;
		this.last = last;
	}

	Name(String full) {
		// does the same work twice
		this(full.split(" ")[0], full.split(" ")[1]);
	}

}
```

=== Inconveniences

Workarounds:

* duplicate argument validation & field assignment
* add an "internal" constructor to forward to
* add static factory method

=== Limitations - Record Edition

To enforce a uniform construction protocol:

Records require all custom constructors +
to (eventually) call the canonical constructor.

⇝ Further limits options.

=== Splitting Arguments

What we want to write:

```java
class Name {

	// [... fields, constructor as before ...]

	Name(String full) {
		String[] names = full.split(" ");
		this(names[0], names[1]);
	}

}
```

(Analogous for records.)

=== Flexible Constructor Bodies

Flexible constructor bodies allow just that!

```java
Constructor(...) {
	// prologue
	// call to this(...) or super(...)
	// epilogue
}
```

Prologue:

* can't touch `this`
* except to assign fields

=== Consequence

With:

* `class A`
* `class B extends A`
* `class C extends B`

Effective constructor execution for `new C()`:

`prologue C` ⇝ `prologue B` ⇝ `prologue A` +
⇝ `Object` ⇝ +
`epilogue A` ⇝ `epilogue B` ⇝ `epilogue C`

=== Prologue

Great to:

* check arguments
* prepare arguments
* split/share arguments
* assign fields

=== Check Arguments

```java
class ThreePartName extends Name {

	protected final String middle;

	ThreePartName(String fst, String mid, String lst) {
		// can't have a middle name without a first name
		requireNonNullNonEmpty(fst);
		this.middle = mid;
		super(fst, lst);
	}

}
```

=== Prepare Arguments

```java
class ThreePartName extends Name {

	protected final String middle;

	ThreePartName(String fst, String mid, String lst) {
		this.middle = mid;
		// shorten first if middle is given
		var shortFst = mid.length() == 1
				? fst.substring(0, 1)
				: fst;
		super(shortFst, lst);
	}

}
```

=== Split Arguments

```java
class ThreePartName extends Name {

	protected final String middle;

	ThreePartName(String full) {
		// split "first middle last" on space (once 🙌🏾)
		var names = full.split(" ");
		this.middle = names[1];
		super(names[0], names[2]);
	}

}
```

=== Surprising Cameo

* Project Valhalla ponders null-restricted fields
* code must never observe such a field being `null`
* has to work with `super()`
* subclass sets non-null fields before `super()`

=== More

* 📝 https://openjdk.org/jeps/513[JEP 513]: Flexible Constructor Bodies
* 🎥 https://www.youtube.com/watch?v=cI-fY9YlmH4[Statements Before `super(...)` and `this(...)`]
* 🎥 https://www.youtube.com/watch?v=IF9l8fYfSnI[Valhalla - Where Are We?] (Brian Goetz - Aug 2024)
