== New Language Features

++++
<table class="toc">
	<tr><td>Private Interface Methods ⑨</td></tr>
	<tr><td>Try-With-Resources ⑨</td></tr>
	<tr><td>Diamond Operator ⑨</td></tr>
	<tr><td>SafeVarargs ⑨</td></tr>
	<tr><td>Deprecation Warnings ⑨</td></tr>
</table>
++++



== New Language Features

++++
<table class="toc">
	<tr class="toc-current"><td>Private Interface Methods ⑨</td></tr>
	<tr><td>Try-With-Resources ⑨</td></tr>
	<tr><td>Diamond Operator ⑨</td></tr>
	<tr><td>SafeVarargs ⑨</td></tr>
	<tr><td>Deprecation Warnings ⑨</td></tr>
</table>
++++

Enabling reuse between default methods.

=== No Reuse

```java
public interface InJava8 {

	default boolean evenSum(int... numbers) {
		return sum(numbers) % 2 == 0;
	}

	default boolean oddSum(int... numbers) {
		return sum(numbers) % 2 == 1;
	}

	default int sum(int[] numbers) {
		return IntStream.of(numbers).sum();
	}

}
```

=== Private Methods

```java
public interface InJava9 {

	private int sum(int[] numbers) {
		return IntStream.of(numbers).sum();
	}

}
```

Just like private methods in abstract classes:

* must be implemented
* can not be overriden
* can only be called in same source file



== New Language Features

++++
<table class="toc">
	<tr><td>Private Interface Methods ⑨</td></tr>
	<tr class="toc-current"><td>Try-With-Resources ⑨</td></tr>
	<tr><td>Diamond Operator ⑨</td></tr>
	<tr><td>SafeVarargs ⑨</td></tr>
	<tr><td>Deprecation Warnings ⑨</td></tr>
</table>
++++

Making `try`-with-resources blocks cleaner.

=== Useless Variable

```java
void doSomethingWith(Connection connection)
		throws Exception {
	try(Connection c = connection) {
		c.doSomething();
	}
}
```

Why is `c` necessary?

=== Why is `c` necessary?

* target of `close()` must be obvious +
⇝ resource should not be reassigned
* easiest if resource is final
* easiest if resource must be assigned +
and can be made implicitly final

```java
try(Connection c = connection)
```

=== Effectively Final Resource

But since Java 8 we have _effectively final_!

This works in Java 9:

```java
void doSomethingWith(Connection connection)
		throws Exception {
	try(connection) {
		connection.doSomething();
	}
}

```

* compiler knows that `connection` is not reassigned
* developers know what _effectively final_ means

[NOTE.speaker]
--
Q: Can instance be created but not assigned? No.
--


== New Language Features

++++
<table class="toc">
	<tr><td>Private Interface Methods ⑨</td></tr>
	<tr><td>Try-With-Resources ⑨</td></tr>
	<tr class="toc-current"><td>Diamond Operator ⑨</td></tr>
	<tr><td>SafeVarargs ⑨</td></tr>
	<tr><td>Deprecation Warnings ⑨</td></tr>
</table>
++++

A little more type inference.

=== Diamond Operator

Maybe the best example:

```java
List<String> strings = new ArrayList<>();
```

* used at a constructor call
* tells Java to infer the parametric type


=== Anonymous Classes

Diamond did not work with anonymous classes:

```java
<T> Box<T> createBox(T content) {
	// we have to put the `T` here :(
	return new Box<T>(content) { };
}
```

Reason are non-denotable types:

* might be inferred by compiler +
  for anonymous classes
* can not be expressed by JVM

=== Infer Denotable Types

Java 9 infers denotable types:

```java
<T> Box<T> createBox(T content) {
	return new Box<>(content) { };
}
```

Gives compile error if type is non-denotable:

```java
Box<?> createCrazyBox(Object content) {
	List<?> innerList = Arrays.asList(content);
	// compile error
	return new Box<>(innerList) { };
}
```



== New Language Features

++++
<table class="toc">
	<tr><td>Private Interface Methods ⑨</td></tr>
	<tr><td>Try-With-Resources ⑨</td></tr>
	<tr><td>Diamond Operator ⑨</td></tr>
	<tr class="toc-current"><td>SafeVarargs ⑨</td></tr>
	<tr><td>Deprecation Warnings ⑨</td></tr>
</table>
++++

One less warning you couldn't do anything about.

=== Heap Pollution

Innocent looking code...

```java
private <T> Optional<T> firstNonNull(T... args) {
	return stream(args)
			.filter(Objects::nonNull)
			.findFirst();
}
```

Compiler warns (on call site, too):

```
Possible heap pollution from
parameterized vararg type
```

=== Heap Pollution?

For generic varargs argument `T... args`, +
you *must not* depend on it being a `T[]`!

```java
private <T> T[] replaceTwoNulls(
		T value, T first, T second) {
	return replaceAllNulls(value, first, second);
}

private <T> T[] replaceAllNulls(T value, T... args) {
	// loop over `args`, replacing `null` with `value`
	return args;
}
```

=== Compiler Warning

Compiler is aware of the problem and warns you.

If you think, everything's under control:

```java
@SafeVarargs
private <T> Optional<T> firstNonNull(T... args) {
	return // [...]
}
```

Or not... In Java 8 this is a compile error!

```
Invalid SafeVarargs annotation. Instance
method <T>firstNonNull(T...) is not final.
```

=== But Why?

The `@SafeVarargs` annotation:

* tells _the caller_ that all is fine
* only makes sense on methods +
that can not be overriden

Which methods can't be overriden? +
⇝ `final` methods

What about `private` methods? +
⇝ Damn! 😭

=== @SafeVarargs on Private&nbsp;Methods

Looong story, here's the point:

In Java 9 `@SafeVarargs` +
can be applied to private methods.



== New Language Features

++++
<table class="toc">
	<tr><td>Private Interface Methods ⑨</td></tr>
	<tr><td>Try-With-Resources ⑨</td></tr>
	<tr><td>Diamond Operator ⑨</td></tr>
	<tr><td>SafeVarargs ⑨</td></tr>
	<tr class="toc-current"><td>Deprecation Warnings ⑨</td></tr>
</table>
++++

_Another_ warning you couldn't do anything about.

=== Deprecation Warnings

Should this code emit a warning?

++++
<div style="height: 350px;">
<div class="listingblock fragment current-display"><div class="content"><pre class="highlight"><code class="java language-java hljs">// LineNumberInputStream is deprecated
<span class="hljs-keyword">import</span> java.io.LineNumberInputStream;


<span class="hljs-keyword">public</span> <span class="hljs-class"><span class="hljs-keyword">class</span> <span class="hljs-title">DeprecatedImports</span> </span>{

    LineNumberInputStream stream;

}</code></pre></div></div>
<div class="listingblock fragment current-display"><div class="content"><pre class="highlight"><code class="java language-java hljs">// LineNumberInputStream is deprecated
<span class="hljs-keyword">import</span> java.io.LineNumberInputStream;

<span class="hljs-meta">@Deprecated</span>
<span class="hljs-keyword">public</span> <span class="hljs-class"><span class="hljs-keyword">class</span> <span class="hljs-title">DeprecatedImports</span> </span>{

    LineNumberInputStream stream;

}</code></pre></div></div></div>
++++

=== Not On Imports

Java 9 no longer emits warnings +
for importing deprecated members.

Warning free:

```java
import java.io.LineNumberInputStream;

@Deprecated
public class DeprecatedImports {

	LineNumberInputStream stream;

}
```
