== New Language Features

++++
<table class="toc">
	<tr><td>Records ⑭</td></tr>
	<tr><td>Pattern Matching ⑭</td></tr>
	<tr><td>Text Blocks ⑬</td></tr>
	<tr><td>Switch Expressions ⑫⑬</td></tr>
	<tr><td>Local-Variable Type Inference ⑩</td></tr>
	<tr><td>All The Small Things... ⑨</td></tr>
</table>
++++



== New Language Features

++++
<table class="toc">
	<tr class="toc-current"><td>Records ⑭</td></tr>
	<tr><td>Pattern Matching ⑭</td></tr>
	<tr><td>Text Blocks ⑬</td></tr>
	<tr><td>Switch Expressions ⑫⑬</td></tr>
	<tr><td>Local-Variable Type Inference ⑩</td></tr>
	<tr><td>All The Small Things... ⑨</td></tr>
</table>
++++

Simple classes ~> simple code

=== Spilling Beans

Typical Java Bean:

```java
public class Range {

	// part I 😀

	private final int low;
	private final int high;

	public Range(int low, int high) {
		this.low = low;
		this.high = high;
	}

}
```

=== Spilling Beans

```java
public class Range {

	// part II 🙄

	public int getLow() {
		return low;
	}

	public int getHigh() {
		return high;
	}

}
```

=== Spilling Beans

```java
public class Range {

	// part III 🤨

	@Override
	public boolean equals(Object o) {
		if (this == o)
			return true;
		if (o == null || getClass() != o.getClass())
			return false;
		Range range = (Range) o;
		return low == range.low &&
				high == range.high;
	}

}
```

=== Spilling Beans

```java
public class Range {

	// part IV 🥴

	@Override
	public int hashCode() {
		return Objects.hash(low, high);
	}

}
```

=== Spilling Beans

```java
public class Range {

	// part V 😭

	@Override
	public String toString() {
		return "[" + low + "; " + high + "]";
	}

}
```

=== "Java is Verbose"

`Range.java` is simple:

* declares type `Range`
* declares two components, `low` and `high`

Takes 44 lines!

* verbose
* room for error
* unexpressive

=== Records

```java
//                these are "components"
public record Range(int low, int high) {

	// compiler generates:
	//  * constructor
	//  * accessors low(), high()
	//  * equals, hashCode, toString

}
```

=== Records

> The API for a record models the state, the whole state, and nothing but the state.

The deal:

* give up encapsulation
* couple API to internal state
* get API for free

=== Records

The benefits:

* no boilerplate for plain "data carriers"
* no room for error
* makes Java more expressive

On to the details!

=== Limited Records

Records are limited classes:

* no inheritance
** can't use `extends`
** are `final`
* component fields are `final`
* no additional fields

=== Customizable Records

Records can be customized:

* override constructor
* add constructors and +
  static factory methods
* override accessors
* add other methods
* override `Object` methods
* implement interfaces

=== Customizable Record

Override constructor:

```java
public Range(int low, int high) {
	if (high < low)
		throw new IllegalArgumentException();
	this.low = low;
	this.high = high;
}
```

=== Customizable Record

Compact form:

```java
// executed before fields are assigned
public Range {
	if (high < low)
		throw new IllegalArgumentException();
}
```

=== Summary

* use records to replace data carriers
* it's not anty-boilerplate pixie dust +
  ⇝ use only when "the deal" makes sense
* beware of limitations
* beware of class-building facilites
* observe ecosystem for adoption



== New Language Features

++++
<table class="toc">
	<tr><td>Records ⑭</td></tr>
	<tr class="toc-current"><td>Pattern Matching ⑭</td></tr>
	<tr><td>Text Blocks ⑬</td></tr>
	<tr><td>Switch Expressions ⑫⑬</td></tr>
	<tr><td>Local-Variable Type Inference ⑩</td></tr>
	<tr><td>All The Small Things... ⑨</td></tr>
</table>
++++

Fewer `if`-s.

=== Pattern Matching

// TODO fill with content




== New Language Features

++++
<table class="toc">
	<tr><td>Records ⑭</td></tr>
	<tr><td>Pattern Matching ⑭</td></tr>
	<tr class="toc-current"><td>Text Blocks ⑬</td></tr>
	<tr><td>Switch Expressions ⑫⑬</td></tr>
	<tr><td>Local-Variable Type Inference ⑩</td></tr>
	<tr><td>All The Small Things... ⑨</td></tr>
</table>
++++

Multiline strings. Finally.

=== Multiline Strings

Text blocks are straightforward:

```java
String haikuBlock = """
	worker bees can leave
	 even drones can fly away
	  the queen is their slave""";
System.out.println(haiku);
// > worker bees can leave
// >  even drones can fly away
// >   the queen is their slave

```

* line breaks are normalized to `\n`
* intentional indentation remains
* accidental indentation is removed

=== Syntax

* can be used in same place +
  as `"string literals"`
* start with `"""` and new line
* end with `"""`
** on the last line of content
** on its own line

Position of closing `"""` decides +
whether string ends with `"\n"`.

=== Vs String Literals

Compare to:

```java
String haikuLiteral = ""
	+ "worker bees can leave\n"
	+ " even drones can fly away\n"
	+ "  the queen is their slave";
```

* `haikuBlock.equals(haikuLiteral)`
* thanks to string interning even +
  `haikuBlock == haikuLiteral`

⇝ No way to discern source at run time!

=== Line Endings

Line ending depends on configuration. +
Source file properties influence semantics?

*Text block lines always end with `\n`!*

Escape sequences are translated afterwards:

```java
String windows = """
    Windows\r
    line\r
    endings\r
    """
```

=== Indentation

Compiler discerns:

* accidental indentation +
  (from code style; gets removed)
* essential indentation +
  (within the string; remains)

How?

=== Accidental Indentation

* closing `"""` are on their own line +
⇝ their indentation is accidental
* otherwise, line with smallest indentation +
⇝ its indentation is accidental

=== Indentation

Accidental vs intentional indentation +
(separated with `|`):

```java
String haikuBlock = """
		|worker bees can leave
		| even drones can fly away
		|  the queen is their slave""";
String haikuBlock = """
	|	worker bees can leave
	|	 even drones can fly away
	|	  the queen is their slave
	""";
```

=== Manual Indentation

To manually manage indentation:

* `String::stripIndent`
* `String::indent`

=== Escape Sequences

Text blocks are not _raw_:

* escape sequences work (e.g. `\r`)
* escape sequences are necessary

But: `"` is not special!

```java
String phrase = """
    {
        greeting: "hello",
        audience: "text blocks",
    }
    """;
```

⇝ Way fewer escapes in HTML/JSON/SQL/etc.

=== More on Text Blocks

* https://blog.codefx.org/java/text-blocks/[Definitive Guide To Text Blocks]
* http://cr.openjdk.java.net/~jlaskey/Strings/TextBlocksGuide_v9.html[Programmer's Guide To Text Blocks]


== New Language Features

++++
<table class="toc">
	<tr><td>Records ⑭</td></tr>
	<tr><td>Pattern Matching ⑭</td></tr>
	<tr><td>Text Blocks ⑬</td></tr>
	<tr class="toc-current"><td>Switch Expressions ⑫⑬</td></tr>
	<tr><td>Local-Variable Type Inference ⑩</td></tr>
	<tr><td>All The Small Things... ⑨</td></tr>
</table>
++++

More powerful `switch`.

=== Switching

Say you're facing https://thedailywtf.com/articles/What_Is_Truth_0x3f_[the dreaded ternary Boolean] ...

```java
public enum TernaryBoolean {
	TRUE,
	FALSE,
	FILE_NOT_FOUND
}
```

\... and want to convert it to a regular `Boolean`.

=== Switch Statement

Before Java 12, you might have done this:

```java
boolean result;
switch (ternaryBool) {
	case TRUE:
		result = true; break;
	case FALSE:
		result = false; break;
	case FILE_NOT_FOUND:
		var ex = new UncheckedIOException(
			"This is ridiculous!",
			new FileNotFoundException());
		throw ex;
	default:
		var ex2 = new IllegalArgumentException(
			"Seriously?! 😠");
		throw ex2;
}
```

=== Switch Statement

Lots of room for improvements:

* default fall-through is annoying
* `result` handling is roundabout
* lacking compiler support is error-prone

=== Switch Statement

This is better:

```java
public boolean convert(TernaryBoolean ternaryBool) {
	switch (ternaryBool) {
		case TRUE:
			return true;
		case FALSE:
			return false;
		case FILE_NOT_FOUND:
			throw new UncheckedIOException(
				"This is ridiculous!",
				new FileNotFoundException());
		default:
			throw new IllegalArgumentException(
				"Seriously?! 😠");
	}
}
```

=== Switch Statement

Better:

* `return` prevents fall-through
* results are created on the spot
* compiler complains on missing branches

But:

* `default` is not really necessary
* creating a method is not always +
  possible or convenient

=== Switch Expression

Enter `switch` expressions:

```java
boolean result = switch(ternaryBool) {
    case TRUE -> true;
    case FALSE -> false;
    case FILE_NOT_FOUND ->
		throw new UncheckedIOException(
			"This is ridiculous!",
			new FileNotFoundException());
};
```

Two things to note:

* `switch` "has a result" +
  ⇝ it's an _expression_, not a _statement_
* lambda-style arrow syntax

=== Preview Feature

*Note*:

In Java 12 & 13, switch expressions are +
a https://blog.codefx.org/java/enable-preview-language-features/[preview language feature]!

* must be enabled with `--enable-preview` +
  (on `javac` and `java`).
* in IntelliJ, set the module's language level to +
  _12 (Preview) - ..._ or _13 (Preview) - ..._
* in Eclipse, go to _Compiler Settings_ +
  and check _Enable preview features_

=== Expression vs Statement

Statement:

```java
if (condition)
    result = doThis();
else
    result = doThat();
```

Expression:

```java
result = condition
	? doThis()
	: doThat();
```

=== Expression vs Statement

Statement:

* imperative construct
* guides computation, but has no result

Expression:

* is computed to a result

=== Expression vs Statement

For `switch`:

* if used with an assignment, +
  `switch` becomes an expression
* if used "stand-alone", it's +
  treated as a statement

This results in different behavior +
(more on that later).

=== Arrow vs Colon

You can use `:` and `\->` with +
expressions and statements, e.g.:

```java
boolean result = switch(ternaryBool) {
    case TRUE: yield true;
    case FALSE: yield false;
    case FILE_NOT_FOUND:
		throw new UncheckedIOException(
			"This is ridiculous!",
			new FileNotFoundException());
};
```

* `switch` is used as an expression
* `yield result` returns `result`
* ⑬ introduced `yield` - in ⑫ it was `break`

=== Arrow vs Colon

Whether you use arrow or colon +
results in different behavior +
(more on that later).

=== Switch Evolution

* general improvements
** multiple case labels
* specifics of arrow form
** no fall-through
** statement blocks
* specifics of expressions
** poly expression
** returning early
** exhaustiveness

=== Multiple Case Labels

Statements and expressions, +
in colon and arrow form +
can use multiple case labels:

```java
String result = switch (ternaryBool) {
	case TRUE, FALSE -> "sane";
	// `default, case FILE_NOT_FOUND -> ...`
	// does not work (neither does other way
	// around), but that makes sense because
	// using only `default` suffices
	default -> "insane";
};
```

=== No Fall-Through

Whether used as statement or expression, +
the arrow form has no fall-through:

```java
switch (ternaryBool) {
	case TRUE, FALSE ->
		System.out.println("Bool was sane");
	// in colon-form, if `ternaryBool` is `TRUE`
	// or `FALSE`, we would see both messages;
	// in arrow-form, only one branch is executed
	default ->
		System.out.println("Bool was insane");
}
```

=== Statement Blocks

Whether used as statement or expression, +
the arrow form can use statement blocks:

```java
boolean result = switch (Bool.random()) {
    case TRUE -> {
        System.out.println("Bool true");
        yield true;
    }
    case FALSE -> {
        System.out.println("Bool false");
        yield false;
    }
	// cases `FILE_NOT_FOUND` and `default`
};
```

=== Statement Blocks

Natural way to create scope:

```java
boolean result = switch (Bool.random()) {
	// cases `TRUE` and `FALSE`
    case FILE_NOT_FOUND -> {
        var ex = new UncheckedIOException(
            "This is ridiculous!",
            new FileNotFoundException());
        throw ex;
    }
    default -> {
        var ex = new IllegalArgumentException(
            "Seriously?! 🤬");
        throw ex;
    }
};
```

=== Poly Expression

A _poly expression_

* has no definitive type
* can be one of several types

Lambdas are poly expressions:

```java
Function<String, String> fun = s -> s + " ";
UnaryOperator<String> op = s -> s + " ";
```

=== Poly Expression

Whether in colon or arrow form, +
a `switch` expression is a poly expression.

How it's type is determined, +
depends on the target type:

```java
// target type known: String
String result = switch (ternaryBool) { ... }
// target type unknown
var result = switch (ternaryBool) { ... }
```

=== Poly Expression

If target type is known, all branches must conform to it:

```java
String result = switch (ternaryBool) {
    case TRUE, FALSE -> "sane";
    default -> "insane";
};
```

If target type is unknown, the compiler infers a type:

```java
// compiler infers super type of `String` and
// `IllegalArgumentException` ~> `Serializable`
var serializableMessage = switch (bool) {
    case TRUE, FALSE -> "sane";
    default -> new IllegalArgumentException("insane");
};
```

=== Returning Early

Whether in colon or arrow form, +
you can't return early from a `switch` expression:

```java
public String sanity(Bool ternaryBool) {
    String result = switch (ternaryBool) {
        // compile error:
		//     "return outside
		//      of enclosing switch expression"
        case TRUE, FALSE -> { return "sane"; }
        default -> { return "This is ridiculous!"; }
    };
}
```

=== Exhaustiveness

Whether in colon or arrow form, +
a `switch` expression checks exhaustiveness:

```java
// compile error:
//     "the switch expression does not cover
//      all possible input values"
boolean result = switch (ternaryBool) {
    case TRUE -> true;
    // no case for `FALSE`
    case FILE_NOT_FOUND ->
		throw new UncheckedIOException(
			"This is ridiculous!",
			new FileNotFoundException());
};
```

=== Exhaustiveness

No compile error for missing `default`:

```java
// compiles without `default` branch because
// all cases for `ternaryBool` are covered
boolean result = switch (ternaryBool) {
    case TRUE -> true;
    case FALSE -> false;
    case FILE_NOT_FOUND ->
		throw new UncheckedIOException(
			"This is ridiculous!",
			new FileNotFoundException());
};
```

Compiler adds in `default` branch.

=== More on `switch`

Definitive Guide To Switch Expressions

* 💻 https://blog.codefx.org/java/switch-expressions/[tiny.cc/java-12-switch]
* ▶ https://www.youtube.com/watch?v=1znHEf3oSNI&list=PL_-IO8LOLuNp2stY1qBUtXlfMdJW7wvfT[tiny.cc/java-12-switch-yt]



== New Language Features

++++
<table class="toc">
	<tr><td>Records ⑭</td></tr>
	<tr><td>Pattern Matching ⑭</td></tr>
	<tr><td>Text Blocks ⑬</td></tr>
	<tr><td>Switch Expressions ⑫⑬</td></tr>
	<tr class="toc-current"><td>Local-Variable Type Inference ⑩</td></tr>
	<tr><td>All The Small Things... ⑨</td></tr>
</table>
++++

Type inference with `var`. +
Less typing, but still strongly typed.


=== Type Duplication

We're used to duplicating +
type information:

```java
URL nipafx = new URL("https://nipafx.dev");
URLConnection connection = nipafx.openConnection();
Reader reader = new BufferedReader(
	new InputStreamReader(
		connection.getInputStream()));
```

Not so bad?

=== Type Duplication

What about this?

```java
No no = new No();
AmountIncrease<BigDecimal> more =
	new BigDecimalAmountIncrease();
HorizontalConnection<LinePosition, LinePosition>
	jumping =
		new HorizontalLinePositionConnection();
Variable variable = new Constant(5);
List<String> names = List.of("Max", "Maria");
```

=== Type Deduplication

Can't somebody else do that? +
Compiler knows the types!

Enter `var`:

```java
var nipafx = new URL("https://nipafx.dev");
var connection = nipafx.openConnection();
var reader = new BufferedReader(
	new InputStreamReader(
		connection.getInputStream()));
```

=== Locality

How much information is used for inference?

* type inference can be +
  arbitrarily complex/powerful
* critical resource is not +
  compiler but developer
* code should be readable +
  (without compiler/IDE)

⇝ Better to keep it simple!

=== "Action at a distance"

```java
// inferred as `int`
var id = 123;
if (id < 100) {
	// very long branch
} else {
	// oh boy, much more code...
}

// now we add this line:
id = "124";
```

What type should `id` be?

Where does the error show up?

=== Rules of `var`

Hence, `var` only works in limited scopes:

[%step]
* compiler infers type from right-hand side +
  ⇝ rhs has to *exist* and *define a type*
* only works for local variables, `for`, `try` +
  ⇝ no `var` on fields or in method signatures
* also on lambda parameters ⑪ +
  ⇝ annotate inferred type on lambda parameters

=== Rules of `var`

Two more:

* not a keyword, but a _reserved type name_ +
  ⇝ variables/fields can be named `var`
* compiler writes type into bytecode +
  ⇝ no run-time component

=== What About Readability?

This *is* about readability!

* less redundancy
* more intermediate variables
* more focus on variable names
* aligned variable names

=== Aligned Variable Names

```java
var no = new No();
var more = new BigDecimalAmountIncrease();
var jumping = new HorizontalLinePositionConnection();
var variable = new Constant(5);
var names = List.of("Max", "Maria");
```

=== What About Readability?

Still think omitting types is always bad?

Ever wrote a lambda without declaring types?

```java
rhetoricalQuestion.answer(yes -> "see my point?");
```

=== Style Guidelines

Principles from the
http://openjdk.java.net/projects/amber/LVTIstyle.html[official style guidelines]:

[%step]
. Reading code is more important than writing it.
. Code should be clear from local reasoning.
. Code readability shouldn't depend on IDEs.
. Explicit types are a tradeoff.

=== Style Guidelines

Guidelines:

[%step]
. Choose variable names that provide useful info.
. Minimize the scope of local variables.
. Consider `var` when the initializer provides sufficient information to the reader.
. Use `var` to break up chained or nested expressions.
. Don't worry too much about "programming to the interface".
. Take care when using `var` with diamonds or generics.
. Take care when using `var` with literals.

=== Style Guidelines

1. Choose variable names that provide useful info.

```java
/* ✘ */ var u = UserRepository.findUser(id);
/* ✔ */ var user = UserRepository.findUser(id);
/* 👍*/ var userToLogIn = UserRepository.findUser(id);
```

=== Style Guidelines

[start=2]
. Minimize the scope of local variables.

```java
// ✘
var id = 123;
if (id < 100) {
	// very long branch
} else {
	// oh boy, much more code...
}
LOGGER.info("... " + id);

// ✔ replace branches with method calls
```

=== Style Guidelines

[start=3]
. Consider `var` when the initializer provides +
  sufficient information to the reader.

```java
/* ✘ */ var user = Repository.find(id);
/* ✔ */ var user = UserRepository.findUser(id);
/* 👍*/ var user = new User(id);
```

=== Style Guidelines

[start=4]
. Use `var` to break up chained or nested expressions.

```java
// ✘
return Canvas
	.activeCanvas()
	.drawings()
	.filter(Drawing::isLine)
	.map(drawing -> (HorizontalConnection) drawing)
		// now we have lines
	.filter(line -> length(line) == 7)
	.map(this::generateSquare)
		// now we have squares
	.map(this::createRandomColoredSquare)
	.map(this::createRandomBorderedSquare)
	.collect(toList());
```

=== Style Guidelines

[start=4]
. Use `var` to break up chained or nested expressions.

```java
// ✔
var lines = Canvas
	.activeCanvas()
	.drawings()
	.filter(Drawing::isLine)
	.map(drawing -> (HorizontalConnection) drawing)
var squares = lines
	.filter(line -> length(line) == 7)
	.map(this::generateSquare);
return squares
	.map(this::createRandomColoredSquare)
	.map(this::createRandomBorderedSquare)
	.collect(toList());
```

=== Style Guidelines

[start=5]
. Don't worry too much about +
  "programming to the interface".

```java
// inferred as `ArrayList` (not `List`),
// but that's ok
var users = new ArrayList<User>();
```

Careful when refactoring:

* extracting methods that use `var`-ed variables +
  puts concrete types into method signatures
* look out and replace with most general type

=== Style Guidelines

[start=6]
. Take care when using `var` with diamonds or generics.

```java
// ✘ infers `ArrayList<Object>`
var users = new ArrayList<>();

// ✔ infers `ArrayList<User>`
var users = new ArrayList<User>();
```

=== Style Guidelines

[start=7]
. Take care when using `var` with literals.

```java
// ✘ when used with `var`, these
//   variables become `int`
byte b = 42;
short s = 42;
long l = 42
```

=== More on `var`

* First Contact With `var` In Java 10 +
💻 https://blog.codefx.org/java/java-10-var-type-inference/[tiny.cc/java-var] /
▶ https://www.youtube.com/watch?v=Le1DbpRZdRQ&index=1&list=PL_-IO8LOLuNp2stY1qBUtXlfMdJW7wvfT[tiny.cc/java-var-yt]
* https://snyk.io/blog/local-type-inference-java-cheat-sheet[cheat sheet] (*⇜ print when getting started!*)
* http://openjdk.java.net/projects/amber/LVTIstyle.html[official style guidelines]
* `var` and ...
** https://blog.codefx.org/java/intersection-types-var/[intersection types]
** https://nipafx.dev/java-var-traits[traits]
** https://blog.codefx.org/java/tricks-var-anonymous-classes/[anonymous classes]



== New Language Features

++++
<table class="toc">
	<tr><td>All The Cool Things... ⑩⑫⑬⑭</td></tr>
	<tr class="toc-current"><td>Private Interface Methods ⑨</td></tr>
	<tr><td>Try-With-Resources ⑨</td></tr>
	<tr><td>Diamond Operator ⑨</td></tr>
	<tr><td>SafeVarargs ⑨</td></tr>
	<tr><td>Deprecation Warnings ⑨</td></tr>
</table>
++++

Enabling reuse between default methods.

=== No Reuse

```java
public interface InJava8 {

	default boolean evenSum(int... numbers) {
		return sum(numbers) % 2 == 0;
	}

	default boolean oddSum(int... numbers) {
		return sum(numbers) % 2 == 1;
	}

	default int sum(int[] numbers) {
		return IntStream.of(numbers).sum();
	}

}
```

=== Private Methods

```java
public interface InJava9 {

	private int sum(int[] numbers) {
		return IntStream.of(numbers).sum();
	}

}
```

Just like private methods in abstract classes:

* must be implemented
* can not be overriden
* can only be called in same source file



== New Language Features

++++
<table class="toc">
	<tr><td>All The Cool Things... ⑩⑫⑬⑭</td></tr>
	<tr><td>Private Interface Methods ⑨</td></tr>
	<tr class="toc-current"><td>Try-With-Resources ⑨</td></tr>
	<tr><td>Diamond Operator ⑨</td></tr>
	<tr><td>SafeVarargs ⑨</td></tr>
	<tr><td>Deprecation Warnings ⑨</td></tr>
</table>
++++

Making `try`-with-resources blocks cleaner.

=== Useless Variable

```java
void doSomethingWith(Connection connection)
		throws Exception {
	try(Connection c = connection) {
		c.doSomething();
	}
}
```

Why is `c` necessary?

=== Why is `c` necessary?

* target of `close()` must be obvious +
⇝ resource should not be reassigned
* easiest if resource is final
* easiest if resource must be assigned +
and can be made implicitly final

```java
try(Connection c = connection)
```

=== Effectively Final Resource

But since Java 8 we have _effectively final_!

This works in Java 9:

```java
void doSomethingWith(Connection connection)
		throws Exception {
	try(connection) {
		connection.doSomething();
	}
}

```

* compiler knows that `connection` is not reassigned
* developers know what _effectively final_ means

[NOTE.speaker]
--
Q: Can instance be created but not assigned? No.
--



== New Language Features

++++
<table class="toc">
	<tr><td>All The Cool Things... ⑩⑫⑬⑭</td></tr>
	<tr><td>Private Interface Methods ⑨</td></tr>
	<tr><td>Try-With-Resources ⑨</td></tr>
	<tr class="toc-current"><td>Diamond Operator ⑨</td></tr>
	<tr><td>SafeVarargs ⑨</td></tr>
	<tr><td>Deprecation Warnings ⑨</td></tr>
</table>
++++

A little more type inference.

=== Diamond Operator

Maybe the best example:

```java
List<String> strings = new ArrayList<>();
```

* used at a constructor call
* tells Java to infer the parametric type


=== Anonymous Classes

Diamond did not work with anonymous classes:

```java
<T> Box<T> createBox(T content) {
	// we have to put the `T` here :(
	return new Box<T>(content) { };
}
```

Reason are non-denotable types:

* might be inferred by compiler +
  for anonymous classes
* can not be expressed by JVM

=== Infer Denotable Types

Java 9 infers denotable types:

```java
<T> Box<T> createBox(T content) {
	return new Box<>(content) { };
}
```

Gives compile error if type is non-denotable:

```java
Box<?> createCrazyBox(Object content) {
	List<?> innerList = Arrays.asList(content);
	// compile error
	return new Box<>(innerList) { };
}
```



== New Language Features

++++
<table class="toc">
	<tr><td>All The Cool Things... ⑩⑫⑬⑭</td></tr>
	<tr><td>Private Interface Methods ⑨</td></tr>
	<tr><td>Try-With-Resources ⑨</td></tr>
	<tr><td>Diamond Operator ⑨</td></tr>
	<tr class="toc-current"><td>SafeVarargs ⑨</td></tr>
	<tr><td>Deprecation Warnings ⑨</td></tr>
</table>
++++

One less warning you couldn't do anything about.

=== Heap Pollution

Innocent looking code...

```java
private <T> Optional<T> firstNonNull(T... args) {
	return stream(args)
			.filter(Objects::nonNull)
			.findFirst();
}
```

Compiler warns (on call site, too):

```
Possible heap pollution from
parameterized vararg type
```

=== Heap Pollution?

For generic varargs argument `T... args`, +
you *must not* depend on it being a `T[]`!

```java
private <T> T[] replaceTwoNulls(
		T value, T first, T second) {
	return replaceAllNulls(value, first, second);
}

private <T> T[] replaceAllNulls(T value, T... args) {
	// loop over `args`, replacing `null` with `value`
	return args;
}
```

=== Compiler Warning

Compiler is aware of the problem and warns you.

If you think, everything's under control:

```java
@SafeVarargs
private <T> Optional<T> firstNonNull(T... args) {
	return // [...]
}
```

Or not... In Java 8 this is a compile error!

```
Invalid SafeVarargs annotation. Instance
method <T>firstNonNull(T...) is not final.
```

=== But Why?

The `@SafeVarargs` annotation:

* tells _the caller_ that all is fine
* only makes sense on methods +
that can not be overriden

Which methods can't be overriden? +
⇝ `final` methods

What about `private` methods? +
⇝ Damn! 😭

=== @SafeVarargs on Private&nbsp;Methods

Looong story, here's the point:

In Java 9 `@SafeVarargs` +
can be applied to private methods.



== New Language Features

++++
<table class="toc">
	<tr><td>All The Cool Things... ⑩⑫⑬⑭</td></tr>
	<tr><td>Private Interface Methods ⑨</td></tr>
	<tr><td>Try-With-Resources ⑨</td></tr>
	<tr><td>Diamond Operator ⑨</td></tr>
	<tr><td>SafeVarargs ⑨</td></tr>
	<tr class="toc-current"><td>Deprecation Warnings ⑨</td></tr>
</table>
++++

_Another_ warning you couldn't do anything about.

=== Deprecation Warnings

Should this code emit a warning?

++++
<div style="height: 350px;">
<div class="listingblock fragment current-display"><div class="content"><pre class="highlight"><code class="java language-java hljs">// LineNumberInputStream is deprecated
<span class="hljs-keyword">import</span> java.io.LineNumberInputStream;


<span class="hljs-keyword">public</span> <span class="hljs-class"><span class="hljs-keyword">class</span> <span class="hljs-title">DeprecatedImports</span> </span>{

    LineNumberInputStream stream;

}</code></pre></div></div>
<div class="listingblock fragment current-display"><div class="content"><pre class="highlight"><code class="java language-java hljs">// LineNumberInputStream is deprecated
<span class="hljs-keyword">import</span> java.io.LineNumberInputStream;

<span class="hljs-meta">@Deprecated</span>
<span class="hljs-keyword">public</span> <span class="hljs-class"><span class="hljs-keyword">class</span> <span class="hljs-title">DeprecatedImports</span> </span>{

    LineNumberInputStream stream;

}</code></pre></div></div></div>
++++

=== Not On Imports

Java 9 no longer emits warnings +
for importing deprecated members.

Warning free:

```java
import java.io.LineNumberInputStream;

@Deprecated
public class DeprecatedImports {

	LineNumberInputStream stream;

}
```
