== {title}

{toc}

=== Patterns so far...

In `instanceof` and `switch`, patterns can:

* match against reference types
* deconstruct records
* nest patterns
* ignore parts of a pattern

In `switch`:

* refine the selection with guarded patterns

=== Patterns so far...

That (plus sealed types) are +
the pattern matching _basics_.

This will be:

* built up with more features
* built out to re-balance the language

=== Case in Point

The `x instanceof Y` operation:

* meant: "is `x` of type `Y`?"
* now means: "does `x` match the pattern `Y`?"

For primitives:

* old semantics made no sense +
  ⇝ no `x instanceof $primitive`
* new semantics _can_ make sense

=== Bound Checks

Example: `int number = 0;`

[%step]
Can `number` be an instance of `byte`?

[%step]
No, it's an `int`.

[%step]
But can its value be a `byte`?

[%step]
Yes!

=== Bound Checks

```java
int x = 0;
if (x instanceof byte b)
	IO.println(b + " in [-128, 127]");
else
	IO.println(x + " not in [-128, 127]");
```

=== More Checks

What's special about 16_777_217?

[%step]
Smallest positive `int` that `float` can't represent.

=== Precision Checks

```java
int x = 16_777_217;
if (x instanceof float f)
	// use `f`
```

=== Tri-state Boolean

```java
Boolean bool = // ...
var emoji = switch (bool) {
	case null -> "";
	case true -> "✅";
	case false -> "❌";
}
```

=== More

* 📝 https://openjdk.org/jeps/530[JEP 530]: Primitive Types in Patterns
* 🎥 https://www.youtube.com/watch?v=_afECXGjfDI[Restoring the Balance with Primitive Patterns]
