== {title}

{toc}

// Multiline strings. Finally.

=== Multiline Strings

Text blocks are straightforward:

```java
String haikuBlock = """
	worker bees can leave
	 even drones can fly away
	  the queen is their slave""";
System.out.println(haiku);
// > worker bees can leave
// >  even drones can fly away
// >   the queen is their slave
```

* line breaks are normalized to `\n`
* intentional indentation remains
* accidental indentation is removed

=== Syntax

* can be used in same place +
  as `"string literals"`
* start with `"""` and new line
* end with `"""`
** on the last line of content
** on its own line

Position of closing `"""` decides +
whether string ends with `"\n"`.

=== Vs String Literals

Compare to:

```java
String haikuLiteral = ""
	+ "worker bees can leave\n"
	+ " even drones can fly away\n"
	+ "  the queen is their slave";
```

* `haikuBlock.equals(haikuLiteral)`
* thanks to string interning even +
  `haikuBlock == haikuLiteral`

⇝ No way to discern source at run time!

=== Line Endings

Line ending depends on configuration. +
Source file properties influence semantics?

*Text block lines always end with `\n`!*

Escape sequences are translated afterwards:

```java
String windows = """
	Windows\r
	line\r
	endings\r
	"""
```

=== Indentation

Compiler discerns:

* accidental indentation +
  (from code style; gets removed)
* essential indentation +
  (within the string; remains)

How?

=== Accidental Indentation

* closing `"""` are on their own line +
⇝ their indentation is accidental
* otherwise, line with smallest indentation +
⇝ its indentation is accidental

=== Indentation

Accidental vs intentional indentation +
(separated with `|`):

```java
String haikuBlock = """
		|worker bees can leave
		| even drones can fly away
		|  the queen is their slave""";
String haikuBlock = """
	|	worker bees can leave
	|	 even drones can fly away
	|	  the queen is their slave
	""";
```

=== Manual Indentation

To manually manage indentation:

* `String::stripIndent`
* `String::indent`

=== Escape Sequences

Text blocks are not _raw_:

* escape sequences work (e.g. `\r`)
* escape sequences are necessary

But: `"` is not special!

```java
String phrase = """
	{
		greeting: "hello",
		audience: "text blocks",
	}
	""";
```

⇝ Way fewer escapes in HTML/JSON/SQL/etc.

// TODO explain trailing white space handling

=== More on Text Blocks

* https://blog.codefx.org/java/text-blocks/[Definitive Guide To Text Blocks]
* https://openjdk.org/projects/amber/guides/text-blocks-guide[Programmer's Guide To Text Blocks]
