== Performance

++++
<table class="toc">
	<tr><td>Application Class-Data Sharing⑩</td></tr>
	<tr><td>Compact Strings ⑨</td></tr>
	<tr><td>Indified String Concatenation ⑨</td></tr>
</table>
++++



== Performance

++++
<table class="toc">
	<tr class="toc-current"><td>Application Class-Data Sharing⑩</td></tr>
	<tr><td>Compact Strings ⑨</td></tr>
	<tr><td>Indified String Concatenation ⑨</td></tr>
</table>
++++

Improving application launch times.

=== Class-Data

JVM steps to execute a class's bytecode:

* looks up class in JAR
* loads bytecode
* verifies bytecode
* stores class-data in +
internal data structure

This takes quite some time.

If classes don't change, the resulting +
class-data is always the same!

=== Class-Data Sharing

Idea behind class-data sharing:

* create class-data once
* dump it into an archive
* reuse the archive in future launches +
  (file is mapped into memory)

=== Effects

My experiments with a large desktop app:

* archive has 250 MB for ~24k classes
* launch time reduced from 15s to 12s

*Bonus*: Archive can be shared across JVMs.

=== Class-Data Sharing

Two variants:

CDS:: Just for JDK classes +
(⑫ includes archive - http://openjdk.java.net/jeps/341[JEP 341])
AppCDS:: JDK + application classes

We will focus on AppCDS.

=== AppCDS - Step #1

Create a list of classes

```sh
$ java
	-XX:+UseAppCDS
	-XX:DumpLoadedClassList=classes.lst
	# class path for dependencies
	-jar app.jar
```

Then, `classes.lst` contains +
slash-separated names of loaded classes.

=== AppCDS - Step #2

Use the list to create the archive:

```sh
$ java
	-XX:+UseAppCDS
	-Xshare:dump
	-XX:SharedClassListFile=classes.lst
	-XX:SharedArchiveFile=app-cds.jsa
	--class-path app.jar # plus dependencies
```

Creates archive `app-cds.jsa`.

=== AppCDS - Step #3

Use the archive:

```sh
$ java
	-XX:+UseAppCDS
	-Xshare:on
	-XX:SharedArchiveFile=app-cds.jsa
	# class path for dependencies
	-jar app.jar
```

=== More On (App)CDS

For more, read this article: +
https://blog.codefx.org/java/application-class-data-sharing/[tiny.cc/app-cds]

* observe sharing with `-Xlog:class+load` +
  (https://blog.codefx.org/java/unified-logging-with-the-xlog-option/[unified logging])
* no wildcards or exploded JARs on class path
* archive invalidation
* module path not yet supported



== Performance

++++
<table class="toc">
	<tr><td>Application Class-Data Sharing⑩</td></tr>
	<tr class="toc-current"><td>Compact Strings ⑨</td></tr>
	<tr><td>Indified String Concatenation ⑨</td></tr>
</table>
++++

Going from UTF-16 to ISO-8859-1.

=== Strings and memory

* 20% - 30% of heap are `char[]` for `String`
* a `char` is UTF-16 code unit ⇝ 2 bytes
* most strings only require ISO-8859-1 ⇝ 1 byte

*10% - 15% of memory is wasted!*

=== Compact Strings

For Java 9, `String` was changed:

* uses `byte[]` instead of `char[]`
* bytes per character:
** 1 if _all_ characters are ISO-8859-1
** 2 otherwise

Only possible because `String` makes +
defensive copies of all arguments.

=== Performance

Simple benchmark: +
(by https://twitter.com/shipilev[Aleksey Shipilëv])

```java
String method = generateString(size);

public String work() {
	return "Calling method \"" + method + "\"";
}
```

Depending on circumstances:

* throughput 1.4x
* garbage less 1.85x



== Performance

++++
<table class="toc">
	<tr><td>Application Class-Data Sharing⑩</td></tr>
	<tr><td>Compact Strings ⑨</td></tr>
	<tr class="toc-current"><td>Indified String Concatenation ⑨</td></tr>
</table>
++++

`"Improving" + "String" + "Concatenation"`

=== String Concatenation

What happens when you run:

```java
String s = greeting + ", " + place + "!";
```

* bytecode uses `StringBuilder`
* JIT may (!) recognize and optimize +
by writing content directly to new `byte[]`
* breaks down quickly +
(e.g. with `long` or `double`)

=== Why Not Create Better Bytecode?

* new optimizations create new bytecode
* new optimizations require recompile
* test matrix _JVMs vs bytecodes_ explodes

=== Why Not Call `String::concat`?

There is no such method.

* `concat(String... args)` requires `toString`
* `concat(Object... args)` requires boxing

Nothing fancy can be done +
because compiler must use public API.

=== Invokedynamic

Invokedynamic came in Java 7:

* compiler creates a recipe
* runtime has to process it
* defers decisions from compiler to runtime

(Used for lambda expressions and in Nashorn.)

=== Indy To The Rescue

With Indy compiler can express +
_"concat these things"_ +
(without boxing!)

JVM executes by writing content +
directly to new `byte[]`.

=== Performance

Depending on circumstances:

* throughput 2.6x
* garbage less 3.4x

(Benchmarks by https://twitter.com/shipilev[Aleksey Shipilëv])

=== Performance Of Indified Compact String Concat

Depending on circumstances:

* throughput 2.9x
* garbage less 6.4x

(Benchmarks by https://twitter.com/shipilev[Aleksey Shipilëv])



== A Mixed Bag Of Performance

In Java 9:

* cgroup-memory limits
* something with interned strings +
and class data sharing (http://openjdk.java.net/jeps/250[JEP 250])
* contended locks (http://openjdk.java.net/jeps/143[JEP 143])
* security manager (http://openjdk.java.net/jeps/232[JEP 232])
* GHASH/RSA computation (http://openjdk.java.net/jeps/246[JEP 246])
* Java 2D rendering (http://openjdk.java.net/jeps/265[JEP 265])
