== {title}

{toc}

=== Preparing your code

Virtual threads:

* always work correctly
* may not scale perfectly

Code changes can improve scalability +
(and maintainability, debuggability, observability).

=== Avoid thread pools

Only pool expensive resources +
but virtual threads are cheap.

⇝ Replace thread pools (for concurrency), +
  with virtual threads plus, e.g., semaphores.

=== With thread pools

```java
// limits concurrent queries but pools 👎🏾
private static final ExecutorService DB_POOL =
	Executors.newFixedThreadPool(16);

public <T> Future<T> queryDatabase(Callable<T> query) {
	return DB_POOL.submit(query);
}
```

=== With semaphore

```java
// limits concurrent queries without pool 👍🏾
private static final Semaphore DB_SEMAPHORE =
	new Semaphore(16);

public <T> T queryDatabase(Callable<T> query)
		throws Exception {
	DB_SEMAPHORE.acquire();
	try {
		return query.call();
	} finally {
		DB_SEMAPHORE.release();
	}
}
```

=== Caveats

To understand virtual thread caveats +
we need to understand how they work.

(Also, it's very interesting.)

=== Under the hood

The Java runtime manages virtual threads:

[%step]
* runs them on a pool of _carrier threads_ +
* on blocking call:
[%step]
** internally calls non-blocking operation
** *_unmounts_ from carrier thread!*
* when call returns: +
[%step]
** _mounts_ to (other) carrier thread
** continues

[NOTE.speaker]
--
* dedicated `ForkJoinPool` in FIFO mode
--

=== The simple web request

Remember the hypothetical request:

. interpret request
. query database (_blocks_)
. process data for response

In a virtual thread:

[%step]
* runtime submits task to carrier thread pool
* when 2. blocks, virtual thread unmounts
* runtime hands carrier thread back to pool
* when 2. unblocks, runtime resubmits task
* virtual thread mounts and continues with 3.

=== Compatibility

Virtual threads work correctly with everything:

* all blocking operations
* `synchronized`
* `Thread`, `currentThread`, etc.
* thread interruption
* thread-locals
* native code

But not all scale perfectly.

// TODO: explain JFR events to discover issues

=== Caveat #1: capture

Despite lots of internal rework
(e.g. JEPs https://openjdk.org/jeps/353[353], https://openjdk.org/jeps/373[373]) +
not all blocking operations unmount.

Specifically, file I/O _captures_ platform threads.

⇝ Compensated by temporarily growing carrier pool.

⚠️ Problematic when capturing operations dominate.

=== Caveat #2: pinning

Some operations _pin_ (operations don't unmount):

* native method call (JNI)
* foreign function call (FFM)

⇝ No compensation

⚠️ Problematic when:

* pinning is frequent
* contains blocking operations


=== Avoid long-running pins

If possible:

* avoid pinning operations
* remove blocking operations +
  from pinning code sections.

=== Caveat #3: thread-locals

Thread-locals can hinder scalability:

* can be inherited
* to keep them thread-local, +
  values are copied
* can occupy lots of memory

(There are also API shortcomings.)

⇝ Refactor to scoped values (https://openjdk.org/jeps/446[JEP 446]).

=== With thread-local

```java
// copies value for each inheriting thread 👎🏾
static final ThreadLocal<Principal> PRINCIPAL =
	new ThreadLocal<>();

public void serve(Request request, Response response) {
	var level = request.isAdmin() ? ADMIN : GUEST;
	var principal = new Principal(level);
	PRINCIPAL.set(principal);
	Application.handle(request, response);
}
```

=== With scoped value

```java
// immutable, so no copies needed 👍🏾
static final ScopedValue<Principal> PRINCIPAL =
	new ScopedValue<>();

public void serve(Request request, Response response) {
	var level = request.isAdmin() ? ADMIN : GUEST;
	var principal = new Principal(level);
	ScopedValue
		.where(PRINCIPAL, principal)
		.run(() -> Application
			.handle(request, response));
}
```

=== Preparing your code

Most importantly:

. replace thread pools with semaphores

Also helpful:

[start=2]
. remove long-running I/O from pinned sections
. replace thread-locals with scoped values
. replace `synchronized` with locks
