== Advanced Java Module System

++++
<h3>Going Deeper...
++++

//***********************************************//
// T R A N S I T I V E   D E P E N D E N C I E S //
//***********************************************//

=== Transitive Dependencies

Not all dependencies are created equal:

* most are used *within* a module
* some are used *on the boundary* +
between modules

Transitive dependencies are about the latter.


=== Exposing dependencies

Example in _calendar_ exposing _surprise_:

[source,java]
----
public static Calendar createWithSurprises(
		List<SurpriseFactory> factories) {
	// ...
}
----

⇝ Module _calendar_ us unusable without _surprise_!

[[TODO, diagram with depending, exposing, exposed module]]


=== Try and Error?

How can users of exposing module +
determine required dependencies?

Try and Error?

No!


=== Implied Readability

Exposing module can mark dependencies +
on exposed modules +
with `requires transitive`:

[source,java]
----
module A {
	requires transitive B;
}
----

* _A_ reads _B_ as usual
* modules reading _A_ will read _B_ +
without having to require it

⇝ _A_ *implies readability* of _B_


=== Implied Readability

Applied to the advent calendar:

[source,java]
----
module calendar {
	requires transitive surprise;
	// ...
}

module factories {
	requires transitive surprise;
	// ...
}
----


=== Further Applications

Implied readability is surprisingly versatile

* aggregator modules
* splitting modules up
* even merging modules
* renaming modules


=== Aggregator Modules

Making it easier to consume +
_calendar_, _factories_, _surprise_:

[source,java]
----
module adventcalendar {
	requires transitive calendar;
	requires transitive factories;
	requires transitive surprise;
}
----


=== Splitting Modules

If _factories_ gets split into +
_api_, _chocolate_, and _quotes_:

[source,java]
----
module factories {
	requires transitive factories.api;
	requires transitive factories.chocolate;
	requires transitive factories.quotes;
}
----


=== Merging Modules

If _calendar_, _factories_, _surprise_ +
are merged into _adventcalendar_:

[source,java]
----
module calendar {
	requires transitive adventcalendar;
}

module factories {
	requires transitive adventcalendar;
}

module surprise {
	requires transitive adventcalendar;
}
----

Careful: Users suddenly depend on a large module!

=== Renaming Modules

If _factories_ becomes _surprisefactories_:

[source,java]
----
module factories {
	requires transitive surprisefactories;
}
----


=== Summary

With `A requires transitive B`:

* _A_ reads _B_
* any module reading _A_ reads _B_

Applications:

* make sure API is usable +
without further dependencies
* aggregator modules
* splitting, merging, renaming modules


//*****************************************//
// O P T I O N L   D E P E N D E N C I E S //
//*****************************************//

=== Optional Dependencies

Not all dependencies are equally required:

* some are needed for a module to function
* some can be absent and code adapts
* are only needed to enhance +
another module's features

Optional dependencies are about the latter two.


=== Use Cases

Adapting code:

* a library may be absent from some deployments
* code is aware and does not call absent modules

Enhancing a module:

* a project may provide usability functions +
for other libraries
* such code can not be called if module absent


=== Conundrum

With what we know so far:

* for code to compile against another module +
that module has to be required
* a required module has to be present +
at launch time

⇝ If a module's types are used +
it has to be present at run time

(Reliable configuration!)


=== Optional Dependencies

Dependency can be marked `requires static`:

[source,java]
----
module A {
	requires static B;
}
----

* at compile time: _A_ requires _B_ as usual
* at run time:
** if _B_ is present, _A_ reads _B_
** otherwise, app can launch +
but access to _B_ can fail


=== Adapting Code

Assuming each factory has its own module, +
_advent_ may not need both all the time:

[source,java]
----
module advent {
	requires calendar;
	requires factories;
	requires static factories.chocolate;
	requires static factories.quote;
}
----


=== Adapting Code

Checking whether module is present:

[source,java]
----
Optional<SurpriseFactory> createChocolateFactory() {
	if (isModulePresent("factories.chocolate"))
		return Optional.of(new ChocolateFactory());
	else
		return Optional.empty();
}
----


=== Enhancing A Module

Hypothetical library _uber-lib_ provides +
usability functions for various libraries.

[source,java]
----
module uber.lib {
	requires static com.google.guava;
	requires static org.apache.commons.lang;
	requires static org.apache.commons.io;
	requires static io.vavr;
	requires static com.aol.cyclops;
}
----

Assumptions:

* nobody calls into Guava part without using Guava
* no runtime checks necessary


=== Summary

With `A requires static B`:

* at compile time: _A_ requires _B_ as usual
* at runtime: _B_ may be absent

Use to prevent absence of optional dependencies +
from preventing application launch:

* modules with code adapting to absense
* utility libraries that aren't called +
without that dependency


//*****************//
// S E R V I C E S //
//*****************//


=== Services

*Consumers* and *implementations* +
of an API should be decoupled.

Service locator pattern:

* service registry as central TODO(vermittler)
* implementors inform registry
* consumers call registry to get implementations

In Java:

* `ServiceLoader` is the registry
* modules can interact with it


=== Services

Module Declarations:

[source,java]
----
// consumer
module A {
	uses service.Interface;
}

// provider
module B {
	provides service.Interface
		with some.Type;
}
----


=== Services

* _A_ never "sees" providers like _B_
* module system picks up all providers
* _A_ can get providers from `ServiceLoader`

[source,java]
----
ServiceLoader.load(service.Interface.class)
----


=== Factory Services

[source,java]
----
module advent {
	requires calendar;
	uses surprise.SurpriseFactory;
}

module factory.chocolate {
	requires surprise;
	provides surprise.SurpriseFactory
		with factory.quote.ChocolateFactory;
}

module factory.quote {
	requires surprise;
	provides surprise.SurpriseFactory
		with factory.quote.QuoteFactory;
}
----


=== Factory Services

[source,java]
----
public static void main(String[] args) {
	List<SurpriseFactory> fac = new ArrayList<>();
	ServiceLoader.load(SurpriseFactory.class)
			.forEach(fac::add);
	Calendar cal = Calendar.createWithSurprises(fac);
	System.out.println(cal.asText());
}
----


=== Summary

To decouple API consumers and providers:

* consumer `uses Service`
* provider `provides Service with Impl`

Module system is service locator; +
request implementations from `ServiceLoader`:

`ServiceLoader.load(Service.class)``


//***********************************//
// Q U A L I F I E D   E X P O R T S //
//***********************************//

=== Qualified Exports

So far, exported packages are visible +
to every reading module.

What if a set of modules wants to share code?


=== Known Problem

Similar to utility classes:

* if class should be visible outside of package, +
it has to be public ⇝ visible to everybody
* if package should be visible outside of module, +
it has to be exported ⇝ visible to everybody

Module system fixes the former. +
What about the latter?


=== Qualified Exports

[source,java]
----
module A {
	exports some.pack to B;
}
----

* _B_ can access `some.pack` +
as if regularly exported
* other modules can not access it +
as if not exported at all


=== Factory Utilities

To ease implementation of `SurpriseFactory`:

* create new module _factory_
* add class `AbstractSurpriseFactory`
* export that package only to +
factory implementation modules

[source,java]
----
module factory {
	requires transitive surprise;
	exports factory
		to factory.chocolate, factory.quote;
}
----


=== Summary

With `A exports pack to B`:

* only _B_ can access types in `pack`
* other modules behave as if `pack` +
not exported

Use to share sensible code between modules.


//*******************************************//
// O P E N   P A C K A G E S / M O D U L E S //
//*******************************************//

=== Reflective Access

Exporting a package makes it public API:

* modules can compile code against it
* clients expect it to be stable

What if a type is only meant +
to be accessed via reflection?

(Think Spring, Hibernate, etc.)


=== Open Packages

[source,java]
----
module A {
	opens some.pack;
}
----

* at compile time: +
types in `some.pack` are not accessible
* at run time: +
_all_ types and members in `some.pack` +
are accessible

A qualified variant (`opens to`) exists.


=== Open Modules

[source,java]
----
open module A {
	// no more `opens` clauses
}
----

The same as open packages +
but for all of them!


=== Summary

With open modules or open packages:

* code can be made accessible +
at compile time only
* particularly valuable to open +
for reflection

Use to make types available for reflection +
without making them public API.


//*************************//
// C O M M A N D   L I N E //
//*************************//

=== Command Line Arguments

The module system is pretty strict but...

* ... not all modules are well-designed
* ... not all use cases were intended

What to do then?

Command Line Arguments to the rescue! +
(I often call them "escape hatches".)


=== Command Line Arguments

All command line flags can be applied +
to `javac` and `java`!

(Which is weird for `--add-opens`.)

When used during compilation, +
they do _not_ change the resulting +
module descriptor!

=== Add Modules

If a module is not required, +
it might not make it into the module graph.

**Help it get there with `--add-modules`:**

[source,bash]
----
	java --module-path mods
#	--add-modules <module>(,<module>)*
		--add-modules factories
		--module advent
----


=== Add Readability Edges

Maybe a module in the graph is not readable +
by another but you need it to be.

**Add readability edges with `--add-reads`:**

[source,bash]
----
	java --module-path mods
#	--add-reads <module>=<target>(,<more>)*
		--add-reads advent=factories
		--module advent
----


=== Add JavaEE Modules

JavaEE modules are not resolved by default! +

* _java.activation_
* _java.annotations.common_
* _java.corba_
* _java.transaction_
* _java.xml.bind_
* _java.xml.ws_

They need to be added with `--add-modules`!


=== Add Exports

A common case:

A module needs types that +
the owning module doesn't export.

**Export them with `--add-exports`:**

[source,bash]
----
	java --module-path mods
#	--add-exports <module>/<package>=<target>
		--add-reads factories/factories.quotes=advent
		--module advent
----

Use target `ALL-UNNAMED` to export to all modules.


=== Open Packages

Another common case:

A module reflects on types from a package that +
the owning module doesn't open.

**Open packages with `add-opens`:**

[source,bash]
----
	java --module-path mods
#	--add-opens <module>/<package>=<target>
		--add-opens factories/factories.quotes=advent
		--module advent
----

Use target `ALL-UNNAMED` to open to all modules.

(It is not possible to open an entire module.)


=== Summary

Edit module graph with:

* `--add-modules` to add modules
* `--add-reads` to add readability edges
* `--add-exports` to export packages to modules
* `--add-opens` to open packages to modules

The latter two accept `ALL-UNNAMED` as target.
