== Why don't they just...

++++
<table class="toc">
	<tr><td>... Let Us Add Fields To Records?!</td></tr>
	<tr class="toc-current"><td>... Let Streams Handle Checked Exceptions?!</td></tr>
	<tr><td>... Introduce Immutable Collections?!</td></tr>
	<tr><td>... Introduce <code>?.</code> For <code>null</code>-safe Member Selection?!</td></tr>
	<tr><td>... Introduce Nullable Types?!</td></tr>
</table>
++++

=== What We Want

Streams that work well with checked exceptions:

[source,java]
----
int compute(String word) throws IOException;
int supercharge(int val) throws InterruptedException;

try {
	List<Integer> supercharged = Stream
		.of("foo", "bar")
		.map(this::compute)
		.map(this::supercharge)
		.toList();
} catch (IOException | InterruptedException ex) {
	// ...
}
----

=== Let's think this through

We need:

* an exception throwing `Function`
* changes to `Stream` methods, +
  so they throw exceptions


=== Attempt #1

Let `map` throw `Exception`:

[source,java]
----
interface Function<IN, OUT> {
	OUT apply(IN input) throws Exception;
}

interface Stream<E> {
	<OUT> Stream<OUT> map(Function<E, OUT> f)
	throws Exception;

	List<E> toList();
}
----

=== Attempt #1

That's not correct:

* streams are lazy
* `map` does not apply the function
* the terminal operation does

⇝ Terminal ops have to declare `throws`.


=== Attempt #2

Let terminal operation throw `Exception`:

[source,java]
----
interface Function<IN, OUT> {
	OUT apply(IN input) throws Exception;
}

interface Stream<E> {
	<OUT> Stream<OUT> map(Function<E, OUT> f)

	List<E> toList() throws Exception;
}
----

=== Attempt #2

[source,java]
----
try {
	List<Integer> supercharged = Stream
		.of("foo", "bar")
		.map(this::compute)
		.map(this::supercharge)
		.toList();
} catch (Exception ex) {
	// which exceptions?
}

List<Integer> supercharged = Stream
	.of("foo", "bar")
	.map(word -> word)
	// compile error: unhandled exception
	.toList();
----

=== Attempt #2

That's awful:

* compiler doesn't know exception type
* we have to catch `Exception` and +
  figure the rest out ourselves
* we _always_ have to catch `Exception`

⇝ Need more specific type than `Exception`.


=== Attempt #3

Capture exception in generic parameter, +
and let terminal operation throw that:

[source,java]
----
interface Function<IN, OUT, EX extends Exception> {
	OUT apply(IN input) throws EX;
}

interface Stream<E, EX extends Exception> {
	<OUT, F_EX extends Exception>
	Stream<OUT, F_EX> map(Function<E, OUT, F_EX> f);

	List<E> toList() throws EX;
}
----

=== Attempt #3

[source,java]
----
try {
	List<Integer> supercharged = Stream
		.of("foo", "bar")
		// ⇝ Stream<Integer, IOException>
		.map(this::compute)
		// ⇝ Stream<Integer, InterruptedException>
		.map(this::supercharge)
		.toList();
} catch (InterruptedException ex) {
	// good
} catch (IOException ex) {
	// isn't declared, so can't be caught
	// ⇝ compile error
}
----

=== Attempt #3

That's not correct:

* only last function's exception type is captured
* other checked exceptions can't be caught

⇝ Need to capture all exception types.


=== Attempt #4

Merge exceptions in generic parameter, +
and let terminal operation throw that:

[source,java]
----
static <
	IN, OUT,
	NEW_EX extends Exception,
	STREAM_EX extends NEW_EX,
	F_EX extends NEW_EX>
Stream<OUT, NEW_EX> map(
		Stream<IN, STREAM_EX> stream,
		Function<IN, OUT, F_EX> f) {
	// ...
}
----

=== Attempt #4

[source,java]
----
try {
	List<Integer> supercharged = Stream
		// ⇝ Stream<Integer, IOException>
		.map(
			// ⇝ Stream<Integer, FileNotFoundException>
			Stream.map(
				// ⇝ Stream<String, RuntimeException>
				Stream.of("foo", "bar"),
				this::throwsFileNotFoundException),
			this::throwsZipException)
		.toList();
} catch (IOException ex) {
	// nice
}
----

=== Attempt #4

[source,java]
----
try {
	List<Integer> supercharged = Stream
		// ⇝ Stream<Integer, Exception>
		.map(
			// ⇝ Stream<Integer, IOException>
			Stream.map(
				// ⇝ Stream<String, RuntimeException>
				Stream.of("foo", "bar"),
				this::compute),
			this::supercharge)
		.toList();
} catch (Exception ex) {
	// argh!
}
----

=== Attempt #4

That's not good:

* common case sucks: +
  `Stream<SomeThing, RuntimeException>`
* `map` as static methods sucks
* catching `Exception` sucks +
  (exceptions don't generalize well)

⇝ Need to keep exception types distinct.


=== Attempt #5

Create multiple `Stream` interfaces +
that differ by number of exceptions:

[source,java]
----
interface Stream<E> {

	<OUT, F_EX extends Exception>
	StreamEx1<OUT, F_EX>
	map(Function<E, OUT, F_EX> f);

	List<E> toList();
}
----

=== Attempt #5

[source,java]
----
interface StreamEx1<E, EX extends Exception> {

	<OUT, F_EX extends Exception>
	StreamEx2<OUT, EX, F_EX>
	map(Function<E, OUT, F_EX> f);

	List<E> toList() throws EX;
}
----

=== Attempt #5

[source,java]
----
interface StreamEx2<E,
		EX0 extends Exception,
		EX1 extends Exception> {

	<OUT, F_EX extends Exception>
	StreamExN<OUT> map(Function<E, OUT, F_EX> f);

	List<E> toList() throws EX0, EX1;
}
----

=== Attempt #5

[source,java]
----
interface StreamExN<E> {

	<OUT, F_EX extends Exception>
	StreamExN<OUT> map(Function<E, OUT, F_EX> f);

	List<E> toList() throws Exception;
}
----

=== Attempt #5

[source,java]
----
try {
	List<Integer> supercharged = Stream
		// ⇝ Stream<String>
		.of("foo", "bar")
		// ⇝ StreamEx1<Integer, IOException>
		.map(this::compute)
		// ⇝ StreamEx2<Integer, IOException,
		//             InterruptedException>
		.map(this::supercharge)
		.toList();
} catch (IOException ex) {
	// good
} catch (InterruptedException ex) {
	// great
}
----

=== Attempt #5

That's correct and usable! +
(Which is a first.)

* but it leads to many additional interfaces
* together with primitive specializations +
  ⇝ combinatorial explosion 💣²
* functions may declare multiple exceptions +
  ⇝ need multiple overloads for all operations +
  ⇝ combinatorial explosion 💣³

⇝ Need variadic generics.


=== Attempt #6

Put all exceptions into one type parameter:

[source,java]
----
interface Function<
		IN, OUT, EXs... extends Exception> {
	OUT apply(IN input) throws EX;
}

interface Stream<E, EXs... extends Exception> {
	<OUT, F_EX extends Exception>
	Stream<OUT, EXs | F_EX>
	map(Function<E, OUT, F_EX> f);

	List<E> toList() throws EXs;
}
----

=== Attempt #6

[source,java]
----
try {
	List<Integer> supercharged = Stream
		// ⇝ Stream<String>
		.of("foo", "bar")
		// ⇝ Stream<Integer, IOException>
		.map(this::compute)
		// ⇝ Stream<Integer, IOException,
		//          InterruptedException>
		.map(this::supercharge)
		.toList();
} catch (InterruptedException ex) {
	// good
} catch (IOException ex) {
	// great
}
----

=== Attempt #6

All around great with one downside:

* Java doesn't allow that
* neither `Function` nor `Stream` compiles

😕


=== Attempt #7

Screw everything, just handle errors via return type:

[source,java]
----
List<Integer> supercharged = Stream
	.of("foo", "bar")
	// ⇝ Stream<Try<Integer>>
	.map(this::compute)
	// ⇝ Stream<Try<Integer>>
	.map(this::supercharge)
	.toList();
----

Already works today. +
https://slides.nipafx.dev/expert-java-8/index.html#/_setting_the_scene[More on that.]


=== Summary

* streams' laziness split in two:
** passing a throwing function (intermediate op)
** handling the exception (terminal op)
* for classic try-catch:
** needs generics to carry exception type(s) forward
** there's no good solution in today's Java
* but there are acceptable alternatives

=== Higher-Level Summary

It doesn't make sense to introduce someting that:

* has serious shortcomings in practice
* prevents a much better solution down the road
* particuarly if an acceptable alternative exists

Just because something isn't perfect, +
doesn't mean every (partial) fix should be implemented.
