== Projects

++++
<table class="toc">
	<tr><td>Versions and Features</td></tr>
	<tr><td>The New World</td></tr>
	<tr class="toc-current"><td>Projects To Look Out For</td></tr>
</table>
++++

Many great features on the horizon!

=== Be aware

Don't focus on versions!

*Focus on projects and JEPs:*

* large features are developed by http://openjdk.java.net/projects/[projects]
* smaller features are proposed by http://openjdk.java.net/jeps/0[JEP] only

Let's have a look at what's coming!

_(Straw-man syntax ahead!)_

=== Many great projects

Amber::
Smaller, productivity-oriented language features
Valhalla::
Generic specialization and value types
Loom::
Fibers and continuations
Metropolis::
Graal and ahead-of-time compilation
// Panama::
// Improved interaction with non-Java code
Sumatra::
Java on the GPU and APU

include::amber.adoc[]

include::valhalla.adoc[]

include::loom.adoc[]

include::sumatra.adoc[]

== Projects

To know what's coming:

* pick a project that interests you
* look out for mentions
* subscribe to the mailing list
* find early access builds and try them
* give feedback

Tell your colleagues about it!
