=== String composition

Composing strings in Java is cumbersome:

```java
String property = "last_name";
String value = "Doe";

// concatenation
String query =
	"SELECT * FROM Person p WHERE p."
		+ property + " = '" + value + "'";
// formatting
String query =
	"SELECT * FROM Person p WHERE p.%s = '%s'"
		.formatted(property, value);
```

[step=1]
Comes with free SQL injection! 😳

=== String interpolation

Why not?

```java
// (fictional syntax!)
String query =
	"SELECT * FROM Person p "
		+ "WHERE p.\{property} = '\{value}'";
```

[step=1]
Also comes with free SQL injection! 😳

=== String interpolation

SQL injections aren't the only concern.

These also need validation and sanitization:

* HTML/XML
* JSON
* YAML
* ...

All follow format-specific rules.

=== String templating

Enter _String Templates_ (https://openjdk.org/jeps/430[JEP 403]):

```java
String query = STR."""
	SELECT * FROM Person p
	WHERE p.\{property} = '\{value}'
	""";
```

Ingredients:

* _template_ with embedded expressions +
  ~> `TemplatedString`
* _template processor_ (e.g. `STR`): +
  transforms `TemplatedString` into `String`*

=== Template procesor STR

```java
String form = STR."""
	Desc     Unit   Qty   Amount
	\{desc} $\{price} \{qty} $\{price * qty}

	Subtotal  $\{price * qty}
	Tax       $\{price * qty * tax}
	Total     $\{price * qty * (1.0 + tax)}
	""";
```
```
Desc     Unit   Qty   Amount
hammer   $7.88  3     $23.64

Subtotal  $23.64
Tax       $3.546
Total     $27.186
```

=== Template processor FMTR

```java
String form = FMTR."""
	Desc        Unit      Qty   Amount
	%-10s\{desc} $%5.2f\{price} %5d\{qty} $%5.2f\{price * qty}

	Subtotal  $%5.2f\{price * qty}
	Tax       $%5.2f\{price * qty * tax}
	Total     $%5.2f\{price * qty * (1.0 + tax)}
	""";
```
```
Desc        Unit      Qty   Amount
hammer      $ 7.88      3   $23.64

Subtotal  $23.64
Tax       $ 3.55
Total     $27.19
```

=== Why strings?

Often, strings are just exchange format, e.g.:

* _start with_: `String` + values
* _validate / sanitize to_: `String`
* _parse to_: `Statement`, `JSONObject`, ...

Why the detour?

=== Custom templating

The `TemplateProcessor` interface:

```java
interface TemplateProcessor<RESULT, EXCEPTION> {
	RESULT apply(TemplatedString s) throws EXCEPTION;
}
```

`RESULT` can be of any type!

////
// text variant:
`interface TemplatedString`:

* `stencil()`: string with placeholders for expressions
* `fragments()`: result of splitting stencil at placeholders
* `values()`: expression values

// code variant:
```java
// represents strings like "Name: \{name}"
interface TemplatedString {
	// methods to access fragments and values
}
```
////

=== Custom templating

```java
Statement query = SQL."""
	SELECT * FROM Person p
	WHERE p.\{property} = '\{value}'
	""";

JSONObject doc = JSON."""
    {
        "name":    "\{name}",
        "phone":   "\{phone}",
        "address": "\{address}"
    };
    """;
```

=== Amber endeavors

Template strings: https://openjdk.org/jeps/430[JEP 430]

Other endeavors:

* finish pattern matching (https://openjdk.java.net/jeps/433[JEP 433])
* add more patterns (https://openjdk.java.net/jeps/405[JEP 405] and more)
* concise method bodies (https://openjdk.java.net/jeps/8209434[JEP draft])
* serialization revamp (https://openjdk.java.net/projects/amber/design-notes/towards-better-serialization[white paper])
