=== Structured programming

* prescribes single entry point +
  and clearly defined exit points
* influenced languages and runtimes

=== Structured concurrency

> When the flow of execution splits into multiple concurrent flows, they rejoin in the same code block.

⇝ Threads are short-lived:

* start when task begins
* end on completion

⇝ Enables parent-child/sibling relationships +
  and logical grouping of threads.

=== Structured concurrency

// TODO: update use of StructuredTaskScope (e.g. ExecutionException -> FailedException)
```java
void handle(Request request, Response response)
		throws InterruptedException {
	// implicitly short-circuits on error
	try (var scope = StructuredTaskScope.open()) {
		var subtaskA = scope.fork(this::taskA);
		var subtaskB = scope.fork(this::taskB);
		// wait explicitly for success
		// (throws errors if there were any)
		scope.join();

		response.send(subtaskA.get() + subtaskB.get());
	} catch (ExecutionException ex) {
		response.fail(ex);
	}
}
```

=== Completion

Use `Joiner` to configure completion:

* how are results collected?
* when are subtasks cancelled?
* when does `join` throw?

Pass to `StructuredTaskScope.open(Joiner)`.

=== Structured concurrency

* forked tasks are children of the scope +
  (visible in thread dumps)
* creates relationship between threads
* success/failure policy can be defined +
  across all children
