== Unlocking the full potential

Virtual threads are cheap and plentiful:

* no pooling necessary
* allows thread per task
* allows liberal creation +
  of threads for subtasks

⇝ Enables new concurrency programming model.

=== A first step

Whenever you need concurrent subtasks, +
spawn virtual threads for each:

```java
private static final ExecutorService VIRTUAL =
	Executors.newVirtualThreadPerTaskExecutor()

void handle(Request request, Response response)
		throws InterruptedException {
	var taskA = VIRTUAL.submit(this::doA);
	var taskB = VIRTUAL.submit(this::doB);
	response.send(taskA.get() + taskB.get());
}
```

[%step]
But we can do (much) better!

=== Structured programming

Emerged when the sea of statements and GOTOs +
became unmaintainable:

* prescribes control structures
* prescribes single entry point +
  and clearly defined exit points
* influenced languages and runtimes

The stricter approach made code (much) clearer!

=== Unstructured concurrency

```java
private static final ExecutorService VIRTUAL =
	Executors.newVirtualThreadPerTaskExecutor()

void handle(Request request, Response response)
		throws InterruptedException {
	// what's the relationship between
	// this and the two spawned threads?
	// what happens when one of them fails?
	var taskA = VIRTUAL.submit(this::doA);
	var taskB = VIRTUAL.submit(this::doB);
	// what if we only need the faster one?
	response.send(taskA.get() + taskB.get());
}
```

=== Structured concurrency

> When the flow of execution splits +
> into multiple concurrent flows, +
> they rejoin in the same code block.

⇝ Thread lifecycle is simple:

* starts when task begins
* ends on completion

⇝ Enables parent-child/sibling relationships +
  and logical grouping of threads.

=== Structured concurrency

```java
void handle(Request request, Response response)
		throws InterruptedException {
	// define explicit success/error handling
	try (var scope = new StructuredTaskScope
			.ShutdownOnFailure()) {
		var taskA = scope.fork(this::doA);
		var taskB = scope.fork(this::doB);
		// wait explicitly until success criteria met
		scope.join();
		scope.throwIfFailed();
		response.send(taskA.get() + taskB.get());
	} catch (ExecutionException ex) {
		response.fail(ex);
	}
}
```

=== Benefits

* success/failure policy can be defined +
  across all children
* create your own (explicit) policies
* forked tasks are children of the scope
* creates relationship between threads

=== Observability

Every task scope thread knows its parent!

During debugging/analyzing, you can:

. navigate that thread's stack
. navigate to its parent thread
. GOTO 1

A task's _entire_ context is visible.
