== The costs

++++
<table class="toc">
	<tr><td>Costs And Benefits</td></tr>
	<tr class="toc-current"><td><ul><li>Costs</li></ul></td></tr>
	<tr><td><ul><li>Benefits</li></ul></td></tr>
	<tr><td><ul><li>Observations</li></ul></td></tr>
	<tr><td>Kinds Of Comments</td></tr>
	<tr><td>Clean Comments</td></tr>
</table>
++++

=== Why most devs hate comments

* initial composition
* maintenance
* confusion
* obstruction

=== Initial composition

Writing a comment is harder...

* the later it is done
* the more complex the topic is
* the more precise the comment is

Usually affordable +
compared to writing code and tests.

=== Maintenance

What to do with comments +
when code changes?

* nothing ⇝ may cause confusion
* update ⇝ takes time
* delete ⇝ wastes past efforts

Whatever schema you decide on +
*maintenance is critical*!

=== Maintenance

* *changing* comments takes little time
* but *finding* them can be hard

⇝ Comments and code must be close!

[NOTE.speaker]
--
* pesky, time-consuming, error-prone
--

=== Confusion

Comments that are...

* outdated
* ambiguous
* lack detail

...cause confusion!

=== Confusion

Costs are unpredictable +
but potentially enormous!

Deteriorates trust in comments.

[NOTE.speaker]
--
* good coding techniques reduce risk
--

=== Obstruction

Takes up screen space.

(Fold that shit!)

=== Why devs _really_ hate comments

* they may be hard to write
* they turn nothing green
* nobody gets a pat on the back +
for a clever comment

++++
<p class="fragment current-visible">Get over it!</p>
++++
